/**
 * A small, real PDF built by hand: a one-page CV with a text layer, an email,
 * a phone number, dated roles and quantified bullets. Embedded rather than
 * kept as a binary file so `deno test` needs no fixture path and no network.
 */
export const SAMPLE_CV_PDF_BASE64 =
  "JVBERi0xLjQKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZyAvUGFnZXMgMiAwIFIgPj4KZW5kb2Jq" +
  "CjIgMCBvYmoKPDwgL1R5cGUgL1BhZ2VzIC9LaWRzIFszIDAgUl0gL0NvdW50IDEgPj4KZW5kb2Jq" +
  "CjMgMCBvYmoKPDwgL1R5cGUgL1BhZ2UgL1BhcmVudCAyIDAgUiAvTWVkaWFCb3ggWzAgMCA2MTIg" +
  "NzkyXSAvQ29udGVudHMgNCAwIFIgL1Jlc291cmNlcyA8PCAvRm9udCA8PCAvRjEgNSAwIFIgPj4g" +
  "Pj4gPj4KZW5kb2JqCjQgMCBvYmoKPDwgL0xlbmd0aCA2MjYgPj4Kc3RyZWFtCkJUCi9GMSAxMSBU" +
  "ZgoxNCBUTAo1NiA3NjAgVGQKKFJpZmF0IEhhc2FuKSBUaiBUKgoocmlmYXQuaGFzYW5AZXhhbXBs" +
  "ZS5jb20gICs4ODAxNzEyMzQ1Njc4KSBUaiBUKgooKSBUaiBUKgooU0tJTExTKSBUaiBUKgooSmF2" +
  "YVNjcmlwdCwgUmVhY3QsIENTUywgSFRNTCwgR2l0LCBUeXBlU2NyaXB0KSBUaiBUKgooKSBUaiBU" +
  "KgooRVhQRVJJRU5DRSkgVGogVCoKKEZyb250ZW5kIGludGVybiwgYkthc2gsIEphbiAyMDI1IC0g" +
  "SnVuIDIwMjUpIFRqIFQqCihCdWlsdCBSZWFjdCBzY3JlZW5zIGFnYWluc3QgUkVTVCBBUElzIGFu" +
  "ZCBjdXQgcGFnZSBsb2FkIHRpbWUgYnkgNDAgcGVyY2VudC4pIFRqIFQqCihTaGlwcGVkIHJlc3Bv" +
  "bnNpdmUgZGVzaWduIGJyZWFrcG9pbnRzIGFjcm9zcyAxMiB0ZW1wbGF0ZXMgdXNpbmcgQ1NTLikg" +
  "VGogVCoKKCkgVGogVCoKKFBST0pFQ1RTKSBUaiBUKgooQ2FtcHVzIG1hcmtldHBsYWNlLCAyMDI0" +
  "KSBUaiBUKgooV3JvdGUgYSBKYXZhU2NyaXB0IGZyb250IGVuZCBzZXJ2aW5nIDMwMCB3ZWVrbHkg" +
  "dXNlcnMgb24gY2FtcHVzLikgVGogVCoKKCkgVGogVCoKKEVEVUNBVElPTikgVGogVCoKKEJTYyBD" +
  "b21wdXRlciBTY2llbmNlLCBCVUVULCAyMDIyIC0gMjAyNikgVGogVCoKRVQKCmVuZHN0cmVhbQpl" +
  "bmRvYmoKNSAwIG9iago8PCAvVHlwZSAvRm9udCAvU3VidHlwZSAvVHlwZTEgL0Jhc2VGb250IC9I" +
  "ZWx2ZXRpY2EgL0VuY29kaW5nIC9XaW5BbnNpRW5jb2RpbmcgPj4KZW5kb2JqCnhyZWYKMCA2CjAw" +
  "MDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDAwOSAwMDAwMCBuIAowMDAwMDAwMDU4IDAwMDAwIG4g" +
  "CjAwMDAwMDAxMTUgMDAwMDAgbiAKMDAwMDAwMDI0MSAwMDAwMCBuIAowMDAwMDAwOTE4IDAwMDAw" +
  "IG4gCnRyYWlsZXIKPDwgL1NpemUgNiAvUm9vdCAxIDAgUiA+PgpzdGFydHhyZWYKMTAxNQolJUVP" +
  "Rgo=";
