# -*- coding: utf-8 -*-
# Source of truth for the ten seeded career paths. Edit here, then run:
#   python3 supabase/seed/career_paths.py > supabase/migrations/0016_seed_career_paths.sql
# Salary figures are entry-level monthly BDT for Dhaka, 2026.

PATHS = [
 dict(slug="frontend-developer", title="Frontend developer", category="software",
  summary="You build the part of a website or app that people actually see and click. Strong demand in Dhaka, and the fastest software path to a first job because your work is visible.",
  salary=(25000,45000), months=8, demand="very high",
  day=["Turn a design into working screens","Fix layout and browser bugs","Connect screens to an API","Review teammates' code"],
  fit=["You like seeing a result immediately","You have an eye for detail","You would rather build than analyse"],
  core=["html","css","javascript","react","git","responsive-design"],
  imp=["typescript","tailwind-css","rest-apis","web-accessibility","browser-devtools","figma"],
  nice=["next-js","redux","web-performance","unit-testing"],
  ms=[
   ("Learn the three basics","HTML, CSS and JavaScript are the whole foundation. Everything after this is a shortcut on top of them.",None,1,[
    ("Build a static page from scratch, no framework","project",4,240,"html"),
    ("Learn CSS flexbox and grid properly","skill",3,180,"css"),
    ("Write 20 small JavaScript exercises","skill",3,300,"javascript"),
    ("Make one page work on a 360px phone screen","skill",3,120,"responsive-design"),
    ("Put your code on GitHub","skill",2,60,"git"),
    ("Add your first three skills to your Tack profile","skill",2,10,None)]),
   ("Build with a framework","One framework, learnt well, beats three learnt badly. React has the most job listings in Bangladesh.","Finish the three basics first",3,[
    ("Learn React components, props and state","skill",4,420,"react"),
    ("Build a to-do app that saves data","project",5,480,"react"),
    ("Learn to fetch data from a public API","skill",3,180,"rest-apis"),
    ("Rebuild an existing Bangladeshi site's homepage","project",5,600,None),
    ("Learn TypeScript basics","skill",3,300,"typescript"),
    ("Deploy one project to a live URL","project",4,120,None)]),
   ("Make it look designed","The gap between a junior and a hireable junior is usually visual polish and accessibility.","Ship one framework project first",4,[
    ("Learn Figma well enough to read a handoff","skill",3,180,"figma"),
    ("Rebuild one project from a real Figma file","project",5,480,"figma"),
    ("Fix the accessibility issues in your best project","skill",4,180,"web-accessibility"),
    ("Get the page loading in under 3 seconds on 3G","skill",4,180,"web-performance"),
    ("Ask two people to use your app and write down what confused them","networking",3,90,None)]),
   ("Prove it in public","Employers in Dhaka hire from what they can see. Three good projects beat a long CV.","Have three deployed projects",6,[
    ("Write a README for each project explaining the problem","cv",3,180,"technical-writing"),
    ("Publish a portfolio site with your three projects","project",5,480,None),
    ("Write one post about something you debugged","networking",3,120,"blog-writing"),
    ("Complete a free frontend certificate","certificate",4,900,None),
    ("Add every project to your Tack profile","project",2,20,None),
    ("Connect with 10 developers on LinkedIn","networking",3,60,"linkedin-marketing")]),
   ("Apply and interview","Applying is a numbers game with a skill attached. Both parts need practice.","Have a portfolio site live",7,[
    ("Write a one-page CV aimed at frontend roles","cv",5,180,None),
    ("Get your CV reviewed by someone working in the field","networking",4,60,None),
    ("Practise 10 JavaScript interview questions","application",4,300,None),
    ("Do three mock interviews in Tack","application",4,120,None),
    ("Apply to 10 junior frontend roles","application",6,240,None),
    ("Follow up on every application after a week","application",3,60,None)])]),

 dict(slug="backend-developer", title="Backend developer", category="software",
  summary="You build the part nobody sees: the database, the API, the logic that keeps data correct. Pays slightly more than frontend at entry level and stays in demand longer.",
  salary=(28000,50000), months=10, demand="very high",
  day=["Write and test API endpoints","Design database tables","Fix production bugs","Make slow queries fast"],
  fit=["You like systems and rules","You enjoy puzzles more than pixels","You are patient with detail"],
  core=["python","sql","rest-apis","git","postgresql","data-structures"],
  imp=["node-js","django","authentication-flows","docker","linux-administration","query-optimisation"],
  nice=["redis","aws","graphql","kubernetes"],
  ms=[
   ("One language, properly","Pick Python or JavaScript and go deep. Switching languages early is the most common way to waste six months.",None,1,[
    ("Choose one language and stick to it for six months","skill",2,15,None),
    ("Learn functions, loops and error handling","skill",3,300,"python"),
    ("Learn lists, dictionaries and sets","skill",3,240,"data-structures"),
    ("Solve 30 beginner algorithm problems","skill",4,600,"algorithms"),
    ("Learn Git and commit every day for a week","skill",3,120,"git"),
    ("Write your first script that reads and writes a file","project",3,120,None)]),
   ("Databases before frameworks","Most junior backend failures are database failures. Learn SQL before you learn an ORM.","Finish one language first",3,[
    ("Learn SELECT, JOIN and GROUP BY until they are automatic","skill",4,360,"sql"),
    ("Design tables for a library system on paper","project",4,180,"database-design"),
    ("Learn primary keys, foreign keys and indexes","skill",4,240,"indexing"),
    ("Install PostgreSQL and load real data into it","skill",3,120,"postgresql"),
    ("Write 15 queries against your own data","skill",3,240,"sql")]),
   ("Build a real API","An API you can demo is worth more than any certificate.","Be comfortable with SQL",4,[
    ("Learn one web framework end to end","skill",5,600,"django"),
    ("Build a CRUD API with authentication","project",6,720,"authentication-flows"),
    ("Write tests for every endpoint","skill",4,300,"unit-testing"),
    ("Add pagination and input validation","skill",3,180,"api-design"),
    ("Document your API so someone else can use it","cv",3,120,"technical-writing"),
    ("Deploy it and keep it running for a month","project",5,240,None)]),
   ("Learn how it runs in production","Knowing Docker and Linux is what separates a student project from a job-ready one.","Have one API deployed",6,[
    ("Learn Linux command line basics","skill",3,240,"linux-administration"),
    ("Containerise your API with Docker","skill",4,240,"docker"),
    ("Set up CI that runs your tests on every push","skill",4,180,"ci-cd"),
    ("Add logging and read your own logs after a bug","skill",3,120,"logging"),
    ("Make one slow query fast and write down how","project",4,180,"query-optimisation"),
    ("Complete a cloud fundamentals certificate","certificate",4,900,"aws")]),
   ("Apply and interview","Backend interviews test SQL and problem solving far more than framework trivia.","Have a deployed, documented API",8,[
    ("Write a CV that leads with your API project","cv",5,180,None),
    ("Practise 20 SQL interview questions","application",5,300,"sql"),
    ("Practise explaining your database design out loud","application",4,120,None),
    ("Do three mock technical interviews in Tack","application",4,150,None),
    ("Apply to 10 junior backend roles","application",6,240,None),
    ("Join two Bangladeshi developer communities","networking",3,60,"networking")])]),

 dict(slug="data-analyst", title="Data analyst", category="data",
  summary="You turn messy company data into a number a manager can act on. Excel and SQL get you hired; Python and dashboards get you promoted.",
  salary=(25000,45000), months=7, demand="high",
  day=["Pull data with SQL","Clean it and check it is right","Build a dashboard","Explain what changed and why"],
  fit=["You like finding the story in numbers","You are careful and sceptical","You can explain things simply"],
  core=["excel","sql","data-cleaning","data-visualisation","statistics"],
  imp=["power-bi","python","pandas","dashboard-design","data-storytelling","kpi-definition"],
  nice=["tableau","a-b-testing","business-intelligence","regression-analysis"],
  ms=[
   ("Own Excel first","Almost every analyst job in Bangladesh still runs on Excel. Being genuinely fast in it is a hireable skill on its own.",None,1,[
    ("Learn VLOOKUP, XLOOKUP and INDEX/MATCH","skill",3,180,"advanced-excel"),
    ("Learn pivot tables until they are automatic","skill",4,180,"excel"),
    ("Clean one messy public dataset by hand","project",4,240,"data-cleaning"),
    ("Build a monthly sales summary sheet","project",4,240,"excel"),
    ("Learn 10 keyboard shortcuts and stop using the mouse","skill",2,60,None)]),
   ("SQL is the job","Every analyst posting asks for SQL. It is also the fastest of these skills to learn.","Be comfortable in Excel",2,[
    ("Learn SELECT, WHERE and ORDER BY","skill",3,180,"sql"),
    ("Learn JOIN properly, all four kinds","skill",4,240,"sql"),
    ("Learn GROUP BY and window functions","skill",4,300,"sql"),
    ("Answer 25 business questions with SQL on a public database","project",5,480,"sql"),
    ("Learn how to check your own query is right","skill",3,120,None)]),
   ("Make it visible","A correct number nobody looks at has no value. Dashboards are how analysts get noticed.","Be comfortable with JOINs",4,[
    ("Learn Power BI or Looker Studio end to end","skill",5,420,"power-bi"),
    ("Build a dashboard from your SQL project","project",5,360,"dashboard-design"),
    ("Learn which chart to use for which question","skill",3,120,"data-visualisation"),
    ("Define three KPIs for a business you know","project",4,120,"kpi-definition"),
    ("Present your dashboard to someone non-technical","networking",4,60,"presentation-skills")]),
   ("Add Python and statistics","This is the step that moves you from reporting to analysis.","Have one dashboard built",5,[
    ("Learn pandas for loading and cleaning data","skill",4,360,"pandas"),
    ("Redo one Excel analysis entirely in Python","project",5,300,"python"),
    ("Learn mean, median, distribution and outliers","skill",3,180,"statistics"),
    ("Learn what a p-value actually means","skill",3,120,"hypothesis-testing"),
    ("Complete a data analytics certificate","certificate",4,1200,None),
    ("Write up one analysis as a short report","cv",4,180,"report-writing")]),
   ("Apply and interview","Analyst interviews are a SQL test plus a case question. Both are practisable.","Have a written-up analysis",6,[
    ("Build a portfolio page with three analyses","project",5,360,None),
    ("Write a CV that names the tools in the job ad","cv",5,180,None),
    ("Practise 20 SQL questions under time pressure","application",5,300,"sql"),
    ("Practise one business case out loud","application",4,120,"analytical-thinking"),
    ("Apply to 10 analyst and MIS roles","application",6,240,None),
    ("Do three mock interviews in Tack","application",4,150,None)])]),

 dict(slug="digital-marketer", title="Digital marketer", category="marketing",
  summary="You get a business in front of the right people online and prove it worked. The lowest barrier to entry of the ten paths, and the easiest to start earning from freelancing.",
  salary=(20000,35000), months=5, demand="high",
  day=["Plan and write posts","Run and adjust paid ads","Read the analytics","Report what worked"],
  fit=["You are curious about why people buy","You write clearly","You are comfortable being measured"],
  core=["social-media-marketing","facebook-ads","content-writing","google-analytics","copywriting"],
  imp=["search-engine-optimisation","google-ads","email-marketing","campaign-planning","canva","funnel-analysis"],
  nice=["conversion-rate-optimisation","marketing-automation","influencer-marketing","e-commerce-marketing"],
  ms=[
   ("Learn the language","Marketing has a vocabulary. Reach, impressions, CTR, CPC, conversion — none of it is hard, all of it is assumed.",None,1,[
    ("Complete the free Meta Blueprint basics","certificate",4,300,"facebook-ads"),
    ("Learn what CTR, CPC, CPM and ROAS mean","skill",3,90,None),
    ("Learn Canva well enough to make a post in 10 minutes","skill",3,180,"canva"),
    ("Write 10 captions for a shop you know","project",3,120,"copywriting"),
    ("Set up a Meta Business Suite account","skill",2,60,"meta-business-suite")]),
   ("Run something real","Nobody hires a marketer who has never spent money or grown an account.","Finish the basics",2,[
    ("Grow one real page from zero for 30 days","project",6,900,"social-media-marketing"),
    ("Run one ad campaign with your own small budget","project",6,300,"facebook-ads"),
    ("Write down what you changed and what happened","cv",4,120,None),
    ("Set up Google Analytics on any site","skill",4,120,"google-analytics"),
    ("Learn to read an analytics report without guessing","skill",4,180,"funnel-analysis")]),
   ("Learn to be found, not just seen","Paid reach stops when the money stops. SEO and email keep working.","Run one real campaign",3,[
    ("Learn keyword research","skill",4,180,"search-engine-optimisation"),
    ("Write one blog post that ranks for a long-tail keyword","project",5,300,"blog-writing"),
    ("Set up an email list and send four emails","project",4,240,"email-marketing"),
    ("Learn basic on-page SEO","skill",3,180,"search-engine-optimisation"),
    ("Audit one Bangladeshi business's online presence","project",5,240,"competitor-analysis")]),
   ("Get paid proof","One paying client is worth more than any certificate in this field.","Have one campaign with real numbers",4,[
    ("Find one small business to manage free for a month","networking",6,600,"client-management"),
    ("Turn the result into a one-page case study","cv",5,180,"report-writing"),
    ("Complete the Google Digital Marketing certificate","certificate",4,1200,None),
    ("Build a portfolio page with two case studies","project",5,300,None),
    ("Ask the client for a written reference","networking",4,30,None)]),
   ("Apply and interview","Marketing interviews ask for numbers. Bring them.","Have one case study written",5,[
    ("Write a CV that leads with campaign results","cv",5,180,None),
    ("Prepare three campaign stories with real numbers","application",5,180,"data-storytelling"),
    ("Practise explaining a campaign that failed","application",4,90,None),
    ("Apply to 10 marketing executive roles","application",6,240,None),
    ("Do three mock interviews in Tack","application",4,150,None),
    ("Connect with 15 marketers on LinkedIn","networking",3,90,"linkedin-marketing")])]),

 dict(slug="hr-executive", title="HR executive", category="business",
  summary="You handle hiring, records, payroll and the people problems that come with them. Steady demand at every company above about thirty staff, and a path that rewards organisation over technical skill.",
  salary=(18000,30000), months=6, demand="moderate",
  day=["Screen CVs and schedule interviews","Keep employee records correct","Answer staff questions","Run onboarding for new joiners"],
  fit=["People come to you with problems already","You are organised and discreet","You like structure and process"],
  core=["recruitment","cv-screening","interviewing","communication","microsoft-word"],
  imp=["onboarding","bangladesh-labour-act","payroll-administration","hris","employee-engagement","advanced-excel"],
  nice=["hr-analytics","performance-management","compensation-and-benefits","workforce-planning"],
  ms=[
   ("Learn the legal floor","In Bangladesh the Labour Act is not optional background reading. Knowing it is a hiring signal on its own.",None,1,[
    ("Read the Bangladesh Labour Act sections on leave and termination","skill",5,300,"bangladesh-labour-act"),
    ("Learn what a compliant appointment letter contains","skill",4,120,"hr-policy-writing"),
    ("Learn the statutory leave types and entitlements","skill",4,120,None),
    ("Write a one-page summary in your own words","cv",3,90,"report-writing"),
    ("Learn the basics of provident fund and gratuity","skill",3,120,None)]),
   ("Learn recruitment properly","Recruitment is the part of HR that gets you hired first, because it is measurable.","Know the legal basics",2,[
    ("Write a job description for a role you understand","project",4,120,"hr-policy-writing"),
    ("Screen 30 real CVs and rank them with reasons","project",5,240,"cv-screening"),
    ("Learn structured interviewing and write 10 questions","skill",4,180,"interviewing"),
    ("Learn to source candidates on LinkedIn and BDJobs","skill",4,180,"talent-sourcing"),
    ("Practise an interview with a friend and get feedback","networking",4,60,None)]),
   ("Get comfortable with the admin","HR runs on spreadsheets and records. Being fast and accurate here is most of the daily job.","Be able to run a screening round",3,[
    ("Learn Excel to pivot-table level","skill",4,240,"advanced-excel"),
    ("Build an employee record template with leave tracking","project",5,240,"excel"),
    ("Learn how monthly payroll is actually calculated","skill",5,240,"payroll-administration"),
    ("Learn one HRIS tool","skill",4,180,"hris"),
    ("Draft an onboarding checklist for a new joiner","project",4,120,"onboarding")]),
   ("Get real exposure","HR is a trust job. A reference from a real workplace outweighs coursework.","Have the admin skills",5,[
    ("Do an HR internship or volunteer at a campus club","project",6,1200,None),
    ("Run recruitment for one club or society position","project",5,300,"recruitment"),
    ("Complete an HR management certificate","certificate",4,900,None),
    ("Write a short policy document for a real group","project",4,180,"hr-policy-writing"),
    ("Ask for a written reference","networking",4,30,None)]),
   ("Apply and interview","HR interviews test judgement with scenarios. Practise answering them out loud.","Have real HR exposure",6,[
    ("Write a CV that names the HR tools and laws you know","cv",5,180,None),
    ("Prepare answers to five difficult-employee scenarios","application",5,180,"conflict-resolution"),
    ("Practise explaining a confidentiality decision","application",4,90,None),
    ("Apply to 10 HR executive and HR intern roles","application",6,240,None),
    ("Do three mock interviews in Tack","application",4,150,None)])]),

 dict(slug="business-analyst", title="Business analyst", category="business",
  summary="You sit between the people who need something and the people who build it, and make sure both mean the same thing. The best-paying non-coding entry point in tech.",
  salary=(30000,55000), months=9, demand="high",
  day=["Interview stakeholders about what they need","Write requirements down precisely","Draw the current and future process","Check what was built matches what was asked"],
  fit=["You ask a lot of questions","You write clearly and precisely","You are comfortable disagreeing politely"],
  core=["business-analysis","requirements-gathering","stakeholder-management","process-mapping","report-writing"],
  imp=["sql","user-story-writing","agile","jira","gap-analysis","excel"],
  nice=["bpmn","product-roadmapping","data-visualisation","feasibility-study"],
  ms=[
   ("Learn to ask and write","The whole job is turning a vague sentence into an unambiguous one. Practise on anything.",None,1,[
    ("Learn the difference between a need, a requirement and a solution","skill",4,120,"business-analysis"),
    ("Write requirements for a campus process you know","project",5,240,"requirements-gathering"),
    ("Learn to write user stories with acceptance criteria","skill",4,180,"user-story-writing"),
    ("Interview three people about one process and find the disagreement","project",5,180,"stakeholder-management"),
    ("Learn to write a one-page summary a busy person will read","skill",4,120,"report-writing")]),
   ("Draw the process","A diagram settles arguments that a document cannot.","Be able to write a requirement",3,[
    ("Learn flowcharts and swimlane diagrams","skill",4,180,"process-mapping"),
    ("Map one real process as-is","project",5,240,"process-mapping"),
    ("Map the same process as it should be","project",5,240,"gap-analysis"),
    ("Learn BPMN notation basics","skill",3,180,"bpmn"),
    ("Present both diagrams to the people who do the work","networking",4,90,"presentation-skills")]),
   ("Learn enough tech to be trusted","You do not need to code. You do need to understand what you are asking for.","Have one process mapped",5,[
    ("Learn SQL to the level of JOIN and GROUP BY","skill",5,360,"sql"),
    ("Learn how an API works and what JSON looks like","skill",4,180,"rest-apis"),
    ("Learn database design basics","skill",4,240,"database-design"),
    ("Learn Agile, Scrum and where a BA fits","skill",4,180,"agile"),
    ("Run a backlog in Jira for a student project","project",4,180,"jira")]),
   ("Do it on a real project","BA is a judgement role and judgement needs a real project to show.","Have technical grounding",7,[
    ("Act as BA for one student or club software project","project",6,1200,"business-analysis"),
    ("Produce a full requirements document for it","cv",5,300,"requirements-gathering"),
    ("Run one sprint planning session","project",4,120,"sprint-planning"),
    ("Complete a business analysis certificate","certificate",4,900,None),
    ("Write a case study of the project","cv",4,180,"report-writing")]),
   ("Apply and interview","BA interviews are case-based. They want to hear you think, not recite.","Have one real BA project",8,[
    ("Write a CV built around outcomes, not duties","cv",5,180,None),
    ("Prepare three requirement-conflict stories","application",5,180,None),
    ("Practise a live process-mapping exercise","application",5,120,"process-mapping"),
    ("Apply to 10 BA and product analyst roles","application",6,240,None),
    ("Do three mock interviews in Tack","application",4,150,None)])]),

 dict(slug="graphic-designer", title="Graphic designer", category="design",
  summary="You make things people look at: logos, posts, packaging, brand systems. Portfolio matters more than degree in this field, and freelancing can start in month two.",
  salary=(18000,32000), months=6, demand="moderate",
  day=["Take a brief and sketch options","Build the artwork","Take feedback and revise","Prepare files for print or web"],
  fit=["You notice when something is misaligned","You can take criticism of your work","You have taste and want to develop it"],
  core=["adobe-illustrator","adobe-photoshop","typography","colour-theory","layout-design"],
  imp=["figma","logo-design","brand-identity","canva","print-design","iconography"],
  nice=["motion-graphics","adobe-after-effects","packaging-design","design-systems"],
  ms=[
   ("Learn to see","Software is a week. Taste is the actual skill, and it is trainable.",None,1,[
    ("Learn typography: pairing, hierarchy, spacing","skill",5,300,"typography"),
    ("Learn colour theory and build five palettes","skill",4,240,"colour-theory"),
    ("Learn grid and alignment","skill",4,180,"layout-design"),
    ("Collect 100 designs you admire and note why","project",4,300,None),
    ("Redraw one existing logo pixel-accurately","project",4,180,"logo-design")]),
   ("Learn the tools","Illustrator for vector, Photoshop for raster, Figma for screens. All three, at working level.","Understand type and colour",2,[
    ("Learn Adobe Illustrator to working level","skill",5,600,"adobe-illustrator"),
    ("Learn Adobe Photoshop to working level","skill",4,480,"adobe-photoshop"),
    ("Learn Figma for screen design","skill",4,300,"figma"),
    ("Learn export settings for print and for web","skill",3,120,"print-design"),
    ("Do 30 daily one-hour design exercises","project",5,1800,None)]),
   ("Build a portfolio with a point of view","Ten random posts is not a portfolio. Three complete projects is.","Be fluent in the tools",4,[
    ("Design a full brand identity for an invented business","project",6,900,"brand-identity"),
    ("Design a 10-post social campaign that holds together","project",5,600,"social-media-marketing"),
    ("Design one packaging or print piece","project",5,480,"packaging-design"),
    ("Write the thinking behind each project, not just the images","cv",4,240,"copywriting"),
    ("Publish a portfolio on Behance or your own site","project",5,300,None)]),
   ("Work with real clients","Client work teaches revision, deadlines and scope — the parts college never covers.","Have three portfolio projects",5,[
    ("Take on three small paid or free client jobs","project",6,900,"client-management"),
    ("Learn to write a design brief and a quote","skill",4,180,"proposal-writing"),
    ("Handle one round of difficult feedback well","skill",4,60,"feedback-receiving"),
    ("Add the client work to your portfolio with permission","cv",4,120,None),
    ("Ask each client for a written testimonial","networking",4,45,None)]),
   ("Apply and interview","Design interviews are portfolio walkthroughs. Practise narrating your decisions.","Have a published portfolio",6,[
    ("Write a one-page CV with a portfolio link at the top","cv",5,120,None),
    ("Practise a 10-minute walkthrough of three projects","application",5,180,"presentation-skills"),
    ("Prepare an answer for 'why this colour, why this type'","application",4,90,None),
    ("Apply to 10 designer and junior designer roles","application",6,240,None),
    ("Do three mock interviews in Tack","application",4,150,None)])]),

 dict(slug="qa-engineer", title="QA engineer", category="software",
  summary="You find the problems before the customer does. The most reliable way into a software company without a strong coding background, and automation raises the ceiling later.",
  salary=(22000,40000), months=7, demand="high",
  day=["Write and run test cases","Report bugs so they can be reproduced","Retest fixes","Automate the tests you run most"],
  fit=["You break things by accident already","You are systematic and stubborn","You write clear instructions"],
  core=["manual-testing","test-case-design","bug-reporting","quality-assurance-processes","attention-to-detail"],
  imp=["api-testing","postman","sql","automated-testing","selenium","regression-testing"],
  nice=["cypress","performance-testing","jmeter","appium"],
  ms=[
   ("Learn to test on purpose","Anyone can click around. Testing is deciding what to click and why before you start.",None,1,[
    ("Learn the software testing life cycle","skill",4,180,"quality-assurance-processes"),
    ("Learn equivalence partitioning and boundary values","skill",4,180,"test-case-design"),
    ("Write 40 test cases for a login screen","project",5,240,"test-case-design"),
    ("Learn to write a bug report someone can reproduce","skill",4,120,"bug-reporting"),
    ("Find and report 20 real bugs in any public app","project",5,360,"manual-testing")]),
   ("Test beneath the screen","API and database testing is where junior QAs become useful fast.","Be able to write test cases",3,[
    ("Learn how HTTP requests and responses work","skill",4,180,"rest-apis"),
    ("Learn Postman and test a public API","project",5,240,"postman"),
    ("Learn SQL well enough to verify data after a test","skill",4,300,"sql"),
    ("Write an API test suite for one endpoint set","project",5,300,"api-testing"),
    ("Learn to test on a 360px Android screen","skill",3,120,"mobile-testing")]),
   ("Automate the boring part","Manual QA is the entry ticket; automation is the pay rise.","Be comfortable with API testing",5,[
    ("Learn Python or JavaScript basics","skill",4,420,"python"),
    ("Learn Selenium or Playwright","skill",5,480,"selenium"),
    ("Automate 10 regression cases","project",6,600,"automated-testing"),
    ("Put your suite in CI so it runs on every push","skill",4,180,"ci-cd"),
    ("Learn to read a failing test and tell flake from real","skill",4,120,None)]),
   ("Work like a team QA","QA is a communication job as much as a technical one.","Have an automated suite",6,[
    ("Test a real student or open-source project for a month","project",6,900,"manual-testing"),
    ("Learn Jira and a real bug workflow","skill",4,180,"jira"),
    ("Write a test plan for one release","cv",5,240,"test-planning"),
    ("Complete an ISTQB foundation-level course","certificate",5,900,None),
    ("Practise arguing for a bug that was closed as won't-fix","networking",3,60,"negotiation")]),
   ("Apply and interview","QA interviews ask you to test something on the spot. Practise thinking out loud.","Have a written test plan",7,[
    ("Write a CV listing tools, types of testing and domains","cv",5,180,None),
    ("Practise 'how would you test this pen' style questions","application",5,150,None),
    ("Prepare three bugs you found and why they mattered","application",4,120,None),
    ("Apply to 10 QA and SQA roles","application",6,240,None),
    ("Do three mock interviews in Tack","application",4,150,None)])]),

 dict(slug="accountant", title="Accountant", category="finance",
  summary="You keep the money records correct and legal. The most stable of the ten paths, with a clear ladder through ACCA or CA if you want it.",
  salary=(18000,32000), months=6, demand="moderate",
  day=["Record transactions","Reconcile accounts","Prepare monthly statements","Handle VAT and tax filings"],
  fit=["You are precise and patient","You like rules that have right answers","You want a career with clear steps"],
  core=["financial-accounting","bookkeeping","journal-entries","advanced-excel","bank-reconciliation"],
  imp=["taxation-bangladesh","vat-compliance","balance-sheet-preparation","tally","accounts-payable","ifrs"],
  nice=["financial-analysis","quickbooks","sap-fico","auditing"],
  ms=[
   ("Get the fundamentals exact","Accounting is unforgiving of approximate understanding. Slow down here and everything after is easy.",None,1,[
    ("Learn the accounting equation until it is obvious","skill",4,180,"financial-accounting"),
    ("Learn debit and credit rules for all five account types","skill",5,240,"journal-entries"),
    ("Post 100 practice journal entries","project",5,480,"journal-entries"),
    ("Prepare a trial balance from scratch","project",4,180,"trial-balance"),
    ("Learn accrual versus cash basis","skill",3,120,None)]),
   ("Build the statements","Being able to produce a full set of statements is the line between student and junior accountant.","Be sound on debits and credits",2,[
    ("Prepare an income statement from a trial balance","project",5,240,"income-statement-preparation"),
    ("Prepare a balance sheet from the same data","project",5,240,"balance-sheet-preparation"),
    ("Prepare a cash flow statement","project",5,300,"cash-flow-statement"),
    ("Do a full bank reconciliation","project",4,180,"bank-reconciliation"),
    ("Learn depreciation methods and apply all three","skill",4,180,"cost-accounting")]),
   ("Learn Bangladeshi compliance","Local tax and VAT knowledge is what makes you employable here specifically.","Be able to produce statements",4,[
    ("Learn the VAT registration and return process","skill",5,300,"vat-compliance"),
    ("Learn personal and corporate income tax basics","skill",5,300,"taxation-bangladesh"),
    ("File one practice income tax return","project",4,180,"income-tax-return"),
    ("Learn what an auditor will ask for","skill",4,180,"auditing"),
    ("Learn IFRS as adopted in Bangladesh, at overview level","skill",4,240,"ifrs")]),
   ("Learn the software","Every firm runs on one of these. Knowing any two makes you portable.","Know local compliance",5,[
    ("Learn Excel to pivot table and lookup level","skill",5,300,"advanced-excel"),
    ("Learn Tally or QuickBooks end to end","skill",5,480,"tally"),
    ("Keep a full month of books for a small real business","project",6,600,"bookkeeping"),
    ("Complete an accounting or ACCA foundation certificate","certificate",5,1200,None),
    ("Build a reusable monthly closing checklist","project",4,120,None)]),
   ("Apply and interview","Accounting interviews test fundamentals directly. There is nowhere to hide, which is good news if you prepared.","Have practical book-keeping experience",6,[
    ("Write a CV listing standards, software and filings you know","cv",5,180,None),
    ("Practise 20 fundamentals questions out loud","application",5,240,"financial-accounting"),
    ("Prepare to explain one adjusting entry from memory","application",4,90,None),
    ("Apply to 10 junior accountant and audit associate roles","application",6,240,None),
    ("Do three mock interviews in Tack","application",4,150,None)])]),

 dict(slug="content-writer", title="Content writer", category="content",
  summary="You write the words a business publishes. The lowest barrier of the ten paths and the easiest to prove — anyone can read your work in a minute.",
  salary=(15000,28000), months=4, demand="moderate",
  day=["Research a topic","Write and edit a draft","Fit it to SEO and brand voice","Take edits without ego"],
  fit=["You already write for fun","You can research quickly","You would rather explain than persuade"],
  core=["content-writing","editing","proofreading","research-writing","english-communication"],
  imp=["blog-writing","search-engine-optimisation","copywriting","social-media-copy","bangla-content-writing"],
  nice=["technical-writing","email-marketing","script-writing","translation"],
  ms=[
   ("Write every day","Volume first, quality second. The quality arrives through the volume.",None,1,[
    ("Write 500 words a day for 30 days","project",6,900,"content-writing"),
    ("Learn to write a headline that is not clickbait","skill",3,120,"copywriting"),
    ("Learn structure: hook, body, close","skill",4,180,"content-writing"),
    ("Learn to cut 20% from any draft","skill",4,120,"editing"),
    ("Read your writing out loud and fix what trips","skill",3,60,"proofreading")]),
   ("Learn to research","The difference between a paid writer and a hobbyist is that the paid one is checkable.","Have a 30-day writing habit",2,[
    ("Learn to find and verify a primary source","skill",4,180,"research-writing"),
    ("Write one 1,200-word researched article with citations","project",5,360,"research-writing"),
    ("Learn to interview someone for an article","skill",4,120,"interviewing"),
    ("Write one piece in Bangla and one in English on the same topic","project",5,300,"bangla-content-writing"),
    ("Learn plagiarism rules and how to paraphrase properly","skill",3,90,None)]),
   ("Write for the internet","Web writing has rules print does not. Learn them or your work is never found.","Have one researched article",3,[
    ("Learn keyword research and search intent","skill",4,180,"search-engine-optimisation"),
    ("Write three posts targeting long-tail keywords","project",5,480,"blog-writing"),
    ("Learn to write for scanning, not reading","skill",3,120,None),
    ("Learn to match a brand voice from a style guide","skill",4,180,None),
    ("Write 20 social captions in three different voices","project",4,240,"social-media-copy")]),
   ("Get published","A byline someone else published beats anything self-published.","Have SEO-aware writing samples",4,[
    ("Publish three pieces on someone else's site or newsletter","project",6,600,None),
    ("Take three paid or free client briefs","project",6,600,"client-management"),
    ("Build a portfolio page with five best pieces","project",5,240,None),
    ("Learn to write a pitch email that gets a reply","skill",4,120,"proposal-writing"),
    ("Ask two editors for a written reference","networking",4,45,None)]),
   ("Apply and interview","Content interviews come with a paid or unpaid writing test. Treat it as the interview.","Have a published portfolio",4,[
    ("Write a CV with your three strongest links at the top","cv",5,120,None),
    ("Prepare for a timed writing test","application",5,120,None),
    ("Practise explaining an edit you disagreed with","application",4,90,None),
    ("Apply to 10 content writer and copywriter roles","application",6,240,None),
    ("Do three mock interviews in Tack","application",4,150,None)])]),
]
