# -*- coding: utf-8 -*-
# Source of truth for the seeded interview question bank. Edit here, then run:
#   python3 supabase/seed/interview_bank.py > supabase/migrations/0069_seed_interview_bank.sql
#
# Why this is written by hand rather than generated by a model:
#
# `interview_question_bank` is a cache keyed on (role, session_type,
# difficulty). The first student to ask for a combination pays one of their
# three daily AI actions and everybody after them gets it free. It has been
# empty since it was created, so every student has been paying for questions
# somebody else already generated.
#
# Seeding it makes interview practice free from the day this lands. Writing the
# questions by hand rather than generating them once also means they are
# reviewable in git, they do not drift when a model changes, and they can be
# specific to the market these students are actually interviewing in — the same
# reason the 261 roadmap tasks were written this way.
#
# Nine questions per role, tagged easy/medium/hard, composed into the three
# difficulty sets. Writing 9 and composing 3 sets of 5 gives better questions
# than writing 15 mediocre ones, and a question that appears in two tiers is
# not a defect: an interviewer asks the same thing of a nervous student and a
# confident one.

E, M, H = "easy", "medium", "hard"

# Behavioural questions are the same whatever the role — nobody asks a
# designer a different version of "tell me about a disagreement". Written once
# and emitted for every role, because the table is keyed by role.
BEHAVIOURAL = [
    (E, "intro", "Tell me about yourself."),
    (E, "motivation", "Why do you want this job, and why here?"),
    (E, "self-awareness", "What are you good at, and what are you working on?"),
    (M, "conflict", "Tell me about a time you disagreed with someone on a team. What happened in the end?"),
    (M, "ownership", "Describe something you built or organised from nothing. What went wrong?"),
    (M, "failure", "Tell me about a deadline you missed. What did you do about it?"),
    (H, "humility", "Tell me about a time you were wrong and someone else was right."),
    (H, "prioritising", "You have three tasks and time for one. How do you choose, and who do you tell?"),
    (H, "direction", "Where do you want to be in five years, and what are you doing about it this month?"),
]

TECHNICAL = {
    "frontend-developer": [
        (E, "fundamentals", "What happens between typing a URL and the page appearing? Take it as far as you can."),
        (E, "css", "What is the difference between padding and margin?"),
        (E, "fundamentals", "You have a list of items from an API. How do you get them onto the page?"),
        (M, "responsive", "A page looks right on your laptop and broken on a 360px phone. How do you find out why?"),
        (M, "react", "What is the difference between state and props, and what makes a component re-render?"),
        (M, "performance", "The page takes six seconds to load on 3G. Where do you look first?"),
        (H, "react", "A form loses what the user typed whenever the parent re-renders. What is happening?"),
        (H, "accessibility", "How would you make a page usable for somebody using a screen reader?"),
        (H, "architecture", "You need the same data on four screens. How do you avoid fetching it four times?"),
    ],
    "backend-developer": [
        (E, "fundamentals", "What is the difference between GET and POST, and when does it matter?"),
        (E, "databases", "What does a database index actually do?"),
        (E, "design", "A user signs up. Walk me through what your API does, step by step."),
        (M, "databases", "A query has become slow as the table grew. How do you find out why?"),
        (M, "security", "What is the difference between authentication and authorisation?"),
        (M, "concurrency", "Two requests try to book the last seat at the same time. What goes wrong?"),
        (H, "debugging", "Your API returns 500s for some users and not others. How do you investigate?"),
        (H, "design", "How would you design the tables behind a food delivery order?"),
        (H, "operations", "You must change a column on a ten-million-row table with no downtime. How?"),
    ],
    "data-analyst": [
        (E, "statistics", "What is the difference between the mean and the median, and when does it matter?"),
        (E, "practice", "You are handed a spreadsheet of sales. What are the first three things you check?"),
        (E, "sql", "Explain what a JOIN does to somebody who has never written SQL."),
        (M, "rigour", "A number in your report looks wrong. Walk me through how you check it."),
        (M, "experiments", "How would you find out which of two versions of a page performs better?"),
        (M, "investigation", "Your dashboard shows a spike last Tuesday. How do you work out whether it is real?"),
        (H, "framing", "A manager asks 'why did revenue drop?'. How do you turn that into an analysis?"),
        (H, "statistics", "What is the difference between correlation and causation? Give an example from your own work."),
        (H, "data quality", "A third of a column is missing. What are your options, and how do you choose?"),
    ],
    "digital-marketer": [
        (E, "metrics", "What is the difference between reach and impressions?"),
        (E, "budget", "You have five thousand taka to spend on ads. How do you decide where?"),
        (E, "local", "What makes a Facebook post do well in Bangladesh specifically?"),
        (M, "funnel", "A campaign got plenty of clicks and no sales. Where do you look?"),
        (M, "measurement", "How do you measure whether content marketing is working?"),
        (M, "judgement", "How would you decide between boosting a post and running a proper campaign?"),
        (H, "diagnosis", "Your cost per acquisition doubled this month. Walk me through finding out why."),
        (H, "strategy", "How would you launch a product to students with no budget at all?"),
        (H, "attribution", "Somebody saw an ad, searched a week later, then bought. Who gets the credit?"),
    ],
    "hr-executive": [
        (E, "screening", "What would you look at first on a CV, and why?"),
        (E, "fundamentals", "What is the difference between recruitment and selection?"),
        (E, "writing", "How would you write a job advert for a junior developer?"),
        (M, "judgement", "Two managers want the same candidate. How do you handle it?"),
        (M, "law", "What does the Bangladesh Labour Act say about notice periods?"),
        (M, "relations", "An employee complains about their manager. What do you do first?"),
        (H, "retention", "Half your new hires leave within six months. How do you find out why?"),
        (H, "process", "Design a fair interview process for a role with three hundred applicants."),
        (H, "difficult", "An employee is underperforming. Take me through the conversation and what you write down."),
    ],
    "business-analyst": [
        (E, "role", "What does a business analyst actually do day to day?"),
        (E, "requirements", "What is a requirement, and what makes a bad one?"),
        (E, "communication", "How would you explain a process to somebody who has never seen it?"),
        (M, "elicitation", "A stakeholder asks for a feature. How do you find out what they actually need?"),
        (M, "modelling", "Map the process of a customer returning a product."),
        (M, "conflict", "Two departments disagree about how a process should work. What do you do?"),
        (H, "prioritising", "How do you decide whether a change is worth making at all?"),
        (H, "delivery", "A project is late and the scope keeps growing. How do you handle it?"),
        (H, "measurement", "How would you prove a process change actually improved something?"),
    ],
    "graphic-designer": [
        (E, "production", "What is the difference between RGB and CMYK, and when does it matter?"),
        (E, "typography", "Why would you choose one typeface over another?"),
        (E, "process", "Walk me through your process from brief to final file."),
        (M, "clients", "A client says 'make it pop'. What do you ask them?"),
        (M, "craft", "How do you design something that works on a billboard and on a phone?"),
        (M, "craft", "What makes a logo still work at sixteen pixels?"),
        (H, "local", "How would you handle Bangla and English in the same layout?"),
        (H, "clients", "A client has rejected three rounds. How do you get the project back on track?"),
        (H, "judgement", "How do you decide when a design is finished?"),
    ],
    "qa-engineer": [
        (E, "fundamentals", "What is the difference between a bug and a feature request?"),
        (E, "practice", "How would you test a login form?"),
        (E, "communication", "What goes into a bug report that a developer can actually act on?"),
        (M, "investigation", "A bug appears on one phone and not another. How do you narrow it down?"),
        (M, "judgement", "When do you automate a test and when do you not bother?"),
        (M, "prioritising", "You have two hours before a release. What do you test?"),
        (H, "debugging", "A test passes on your machine and fails in CI. How do you investigate?"),
        (H, "practice", "How would you test something that only breaks under load?"),
        (H, "process", "A bug reached production. How do you stop that class of bug reaching it again?"),
    ],
    "accountant": [
        (E, "fundamentals", "What is the difference between cash and accrual accounting?"),
        (E, "fundamentals", "Explain debit and credit to somebody who has never studied accounting."),
        (E, "statements", "What is on a balance sheet, and what is not?"),
        (M, "practice", "The bank statement does not match the ledger. How do you find the difference?"),
        (M, "local", "What is VAT, and how does it work in Bangladesh?"),
        (M, "judgement", "An invoice arrives after year end. What do you do with it?"),
        (H, "process", "Take me through closing the books for a month."),
        (H, "ethics", "A manager asks you to record something you believe is wrong. What do you do?"),
        (H, "communication", "Explain a cash flow problem to somebody who is not an accountant."),
    ],
    "content-writer": [
        (E, "audience", "How do you decide who you are writing for?"),
        (E, "craft", "What makes a headline work?"),
        (E, "research", "How do you research a topic you know nothing about?"),
        (M, "seo", "How do you write for search without writing badly?"),
        (M, "measurement", "An article got no readers. How do you find out why?"),
        (M, "voice", "How do you keep one brand voice across several writers?"),
        (H, "craft", "Turn a technical document into something a customer can read. How do you start?"),
        (H, "editing", "How do you decide what to cut?"),
        (H, "local", "How do you write for a Bangladeshi audience in English without sounding foreign?"),
    ],
}

# How a difficulty tier is built from the pool of nine. An easy set is not only
# easy questions: an interview opens gently and gets harder, and a student who
# practises three easy questions in a row has not practised an interview.
COMPOSITION = {
    "easy":   [E, E, E, M, M],
    "medium": [E, M, M, M, H],
    "hard":   [M, M, H, H, H],
}


def pick(pool, wanted):
    """Takes the requested tiers in order, without repeating within a set."""
    by_tier = {E: [], M: [], H: []}
    for tier, category, text in pool:
        by_tier[tier].append((category, text))

    used, out = set(), []
    for tier in wanted:
        for category, text in by_tier[tier]:
            if text not in used:
                used.add(text)
                out.append({"question": text, "category": category})
                break
    return out


def sql_string(value):
    return "'" + value.replace("'", "''") + "'"


def json_literal(questions):
    import json
    return sql_string(json.dumps(questions, ensure_ascii=False))


COMPANIES = [
    ("bkash", "bKash", "Mobile financial services, and the largest employer of "
     "junior engineers in Dhaka. Interviews lean heavily on fundamentals and on "
     "whether you can reason about money moving between accounts.",
     ["Why does a payment system care so much about idempotency?",
      "A transfer is debited but not credited. What do you do first?",
      "How would you explain bKash to somebody who has never used a bank?",
      "What would worry you about handling other people's money?"]),
    ("grameenphone", "Grameenphone", "The largest mobile operator. A long, "
     "structured process with an aptitude test before anybody technical sees you.",
     ["Why telecom, and why Grameenphone?",
      "Tell me about a time you worked with somebody difficult.",
      "How would you explain a technical problem to a non-technical manager?",
      "Where do you think mobile data in Bangladesh goes in the next five years?"]),
    ("pathao", "Pathao", "Ride-hailing, delivery and courier. Interviews are "
     "practical and fast, and they care whether you have actually built things.",
     ["Show me something you built. Why did you build it that way?",
      "How would you design the screen a rider sees while waiting for a trip?",
      "A driver and a customer disagree about a fare. What does the system do?",
      "What would you measure to know whether a delivery is going badly?"]),
    ("brac", "BRAC", "The largest NGO in the world, and a serious technology "
     "employer. Expect questions about impact alongside the technical ones.",
     ["Why development work rather than a private company?",
      "How would you collect data from field workers with no reliable internet?",
      "Tell me about a time you had to work with very little.",
      "How do you know whether a programme is actually helping anyone?"]),
    ("robi", "Robi Axiata", "A mobile operator with a large graduate intake. "
     "Structured, competency-based interviews.",
     ["Tell me about a time you led something without being in charge.",
      "How do you handle being given a target you think is unrealistic?",
      "What do you do in the first week of a job where nobody explains anything?",
      "Describe a decision you made with incomplete information."]),
    ("shohoz", "Shohoz", "Tickets, rides and logistics. A smaller team, so "
     "interviews test breadth and whether you can work without much direction.",
     ["You are the only person on a feature. How do you decide what to build first?",
      "How would you handle a launch during Eid traffic?",
      "What do you do when the requirements change halfway through?",
      "Tell me about something you shipped that nobody asked you to."]),
]


def main():
    rows = []
    for role in sorted(TECHNICAL):
        technical_pool = TECHNICAL[role]
        for difficulty, wanted in COMPOSITION.items():
            behavioural = pick(BEHAVIOURAL, wanted)
            technical = pick(technical_pool, wanted)
            # A mixed interview is what a student actually sits: a couple of
            # questions about them, then the ones about the work.
            mixed = behavioural[:2] + technical[:3]

            for session_type, questions in (
                ("behavioural", behavioural),
                ("technical", technical),
                ("mixed", mixed),
            ):
                rows.append((role, session_type, difficulty, questions))

    print("-- Generated by supabase/seed/interview_bank.py. Do not edit by hand.")
    print("--")
    print("-- interview_question_bank is a cache: the first student to ask for a")
    print("-- (role, type, difficulty) pays one of three daily AI actions, and")
    print("-- everybody after them gets it free. It has been empty since it was")
    print("-- created in 0008, so every student has been paying for questions the")
    print("-- last one already generated.")
    print("--")
    print("-- Seeding it makes interview practice cost nothing from today. The")
    print("-- questions are hand-written so they are reviewable in git, do not")
    print("-- drift when a model changes, and can be specific to the market these")
    print("-- students are actually interviewing in.")
    print()
    print(f"-- {len(rows)} sets: 10 roles x 3 session types x 3 difficulties.")
    print()

    print("insert into public.interview_question_bank")
    print("  (role_slug, session_type, difficulty, questions)")
    print("values")
    values = []
    for role, session_type, difficulty, questions in rows:
        values.append(
            f"  ({sql_string(role)}, {sql_string(session_type)}::interview_type, "
            f"{sql_string(difficulty)}::difficulty_level, {json_literal(questions)}::jsonb)"
        )
    print(",\n".join(values))
    print("on conflict (role_slug, session_type, difficulty) do update")
    print("  set questions = excluded.questions;")
    print()

    # ---------------------------------------------------------------- companies
    print("-- ------------------------------------------------------ company packs")
    print("--")
    print("-- What a student actually wants the night before: not 'behavioural,")
    print("-- medium' but 'I have an interview at bKash on Thursday'. Public")
    print("-- reference data like career_paths, readable by any signed-in student.")
    print("""
create table if not exists public.company_interview_packs (
  slug       text primary key,
  name       text not null,
  about      text not null,
  questions  jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.company_interview_packs enable row level security;
alter table public.company_interview_packs force row level security;

drop policy if exists company_interview_packs_read on public.company_interview_packs;
create policy company_interview_packs_read on public.company_interview_packs
  for select to authenticated using (true);

comment on table public.company_interview_packs is
  'Employers Bangladeshi students actually apply to, and what each is known '
  'to ask. Reference data, seeded, not user-generated.';
""")
    print("insert into public.company_interview_packs (slug, name, about, questions)")
    print("values")
    company_values = []
    for slug, name, about, questions in COMPANIES:
        payload = [{"question": q, "category": "company"} for q in questions]
        company_values.append(
            f"  ({sql_string(slug)}, {sql_string(name)}, {sql_string(about)}, "
            f"{json_literal(payload)}::jsonb)"
        )
    print(",\n".join(company_values))
    print("on conflict (slug) do update set")
    print("  name = excluded.name, about = excluded.about,")
    print("  questions = excluded.questions;")
    print()

    print("""-- ------------------------------------------------------------------- checked
do $$
declare
  v_sets int;
  v_thin int;
begin
  select count(*) into v_sets from public.interview_question_bank;
  if v_sets < 90 then
    raise exception 'expected 90 seeded sets, found %', v_sets;
  end if;

  -- The endpoint slices to the requested count, which defaults to five. A set
  -- with fewer would silently hand a student a shorter interview.
  select count(*) into v_thin from public.interview_question_bank
   where jsonb_array_length(questions) < 5;
  if v_thin > 0 then
    raise exception '% seeded sets have fewer than five questions', v_thin;
  end if;

  if (select count(*) from public.company_interview_packs) < 6 then
    raise exception 'the company packs did not seed';
  end if;
end $$;""")


if __name__ == "__main__":
    main()
