-- Reference vocabulary for the Bangladeshi entry-level market.
-- Generated from supabase/seed/skills.txt; edit that file and regenerate.
insert into public.skills (slug, name, category) values
  ('python', 'Python', 'programming'),
  ('java', 'Java', 'programming'),
  ('javascript', 'JavaScript', 'programming'),
  ('typescript', 'TypeScript', 'programming'),
  ('c', 'C', 'programming'),
  ('php', 'PHP', 'programming'),
  ('ruby', 'Ruby', 'programming'),
  ('go', 'Go', 'programming'),
  ('rust', 'Rust', 'programming'),
  ('kotlin', 'Kotlin', 'programming'),
  ('swift', 'Swift', 'programming'),
  ('dart', 'Dart', 'programming'),
  ('r', 'R', 'programming'),
  ('scala', 'Scala', 'programming'),
  ('perl', 'Perl', 'programming'),
  ('matlab', 'MATLAB', 'programming'),
  ('objective-c', 'Objective-C', 'programming'),
  ('shell-scripting', 'Shell scripting', 'programming'),
  ('bash', 'Bash', 'programming'),
  ('powershell', 'PowerShell', 'programming'),
  ('assembly', 'Assembly', 'programming'),
  ('vba', 'VBA', 'programming'),
  ('solidity', 'Solidity', 'programming'),
  ('object-oriented-programming', 'Object-oriented programming', 'programming'),
  ('functional-programming', 'Functional programming', 'programming'),
  ('data-structures', 'Data structures', 'programming'),
  ('algorithms', 'Algorithms', 'programming'),
  ('design-patterns', 'Design patterns', 'programming'),
  ('concurrency', 'Concurrency', 'programming'),
  ('memory-management', 'Memory management', 'programming'),
  ('regular-expressions', 'Regular expressions', 'programming'),
  ('debugging', 'Debugging', 'programming'),
  ('code-review', 'Code review', 'programming'),
  ('unit-testing', 'Unit testing', 'programming'),
  ('test-driven-development', 'Test-driven development', 'programming'),
  ('clean-code', 'Clean code', 'programming'),
  ('refactoring', 'Refactoring', 'programming'),
  ('api-design', 'API design', 'programming'),
  ('html', 'HTML', 'web'),
  ('css', 'CSS', 'web'),
  ('sass', 'Sass', 'web'),
  ('tailwind-css', 'Tailwind CSS', 'web'),
  ('bootstrap', 'Bootstrap', 'web'),
  ('react', 'React', 'web'),
  ('next-js', 'Next.js', 'web'),
  ('vue-js', 'Vue.js', 'web'),
  ('nuxt', 'Nuxt', 'web'),
  ('angular', 'Angular', 'web'),
  ('svelte', 'Svelte', 'web'),
  ('jquery', 'jQuery', 'web'),
  ('redux', 'Redux', 'web'),
  ('node-js', 'Node.js', 'web'),
  ('express-js', 'Express.js', 'web'),
  ('nestjs', 'NestJS', 'web'),
  ('django', 'Django', 'web'),
  ('flask', 'Flask', 'web'),
  ('fastapi', 'FastAPI', 'web'),
  ('laravel', 'Laravel', 'web'),
  ('codeigniter', 'CodeIgniter', 'web'),
  ('spring-boot', 'Spring Boot', 'web'),
  ('asp-net', 'ASP.NET', 'web'),
  ('ruby-on-rails', 'Ruby on Rails', 'web'),
  ('rest-apis', 'REST APIs', 'web'),
  ('graphql', 'GraphQL', 'web'),
  ('websockets', 'WebSockets', 'web'),
  ('web-accessibility', 'Web accessibility', 'web'),
  ('responsive-design', 'Responsive design', 'web'),
  ('progressive-web-apps', 'Progressive web apps', 'web'),
  ('server-side-rendering', 'Server-side rendering', 'web'),
  ('web-performance', 'Web performance', 'web'),
  ('browser-devtools', 'Browser DevTools', 'web'),
  ('webpack', 'Webpack', 'web'),
  ('vite', 'Vite', 'web'),
  ('npm', 'npm', 'web'),
  ('authentication-flows', 'Authentication flows', 'web'),
  ('oauth', 'OAuth', 'web'),
  ('jwt', 'JWT', 'web'),
  ('session-management', 'Session management', 'web'),
  ('flutter', 'Flutter', 'mobile'),
  ('react-native', 'React Native', 'mobile'),
  ('android-development', 'Android development', 'mobile'),
  ('ios-development', 'iOS development', 'mobile'),
  ('swiftui', 'SwiftUI', 'mobile'),
  ('jetpack-compose', 'Jetpack Compose', 'mobile'),
  ('kotlin-multiplatform', 'Kotlin Multiplatform', 'mobile'),
  ('xamarin', 'Xamarin', 'mobile'),
  ('ionic', 'Ionic', 'mobile'),
  ('mobile-ui-design', 'Mobile UI design', 'mobile'),
  ('push-notifications', 'Push notifications', 'mobile'),
  ('offline-first-apps', 'Offline-first apps', 'mobile'),
  ('app-store-deployment', 'App Store deployment', 'mobile'),
  ('google-play-deployment', 'Google Play deployment', 'mobile'),
  ('firebase', 'Firebase', 'mobile'),
  ('mobile-testing', 'Mobile testing', 'mobile'),
  ('deep-linking', 'Deep linking', 'mobile'),
  ('in-app-purchases', 'In-app purchases', 'mobile'),
  ('sql', 'SQL', 'data'),
  ('postgresql', 'PostgreSQL', 'data'),
  ('mysql', 'MySQL', 'data'),
  ('sqlite', 'SQLite', 'data'),
  ('mongodb', 'MongoDB', 'data'),
  ('redis', 'Redis', 'data'),
  ('oracle-database', 'Oracle Database', 'data'),
  ('microsoft-sql-server', 'Microsoft SQL Server', 'data'),
  ('database-design', 'Database design', 'data'),
  ('normalisation', 'Normalisation', 'data'),
  ('query-optimisation', 'Query optimisation', 'data'),
  ('indexing', 'Indexing', 'data'),
  ('stored-procedures', 'Stored procedures', 'data'),
  ('data-modelling', 'Data modelling', 'data'),
  ('etl', 'ETL', 'data'),
  ('data-warehousing', 'Data warehousing', 'data'),
  ('apache-spark', 'Apache Spark', 'data'),
  ('hadoop', 'Hadoop', 'data'),
  ('pandas', 'Pandas', 'data'),
  ('numpy', 'NumPy', 'data'),
  ('data-cleaning', 'Data cleaning', 'data'),
  ('data-visualisation', 'Data visualisation', 'data'),
  ('power-bi', 'Power BI', 'data'),
  ('tableau', 'Tableau', 'data'),
  ('looker-studio', 'Looker Studio', 'data'),
  ('excel', 'Excel', 'data'),
  ('advanced-excel', 'Advanced Excel', 'data'),
  ('google-sheets', 'Google Sheets', 'data'),
  ('statistics', 'Statistics', 'data'),
  ('probability', 'Probability', 'data'),
  ('hypothesis-testing', 'Hypothesis testing', 'data'),
  ('regression-analysis', 'Regression analysis', 'data'),
  ('a-b-testing', 'A/B testing', 'data'),
  ('machine-learning', 'Machine learning', 'data'),
  ('deep-learning', 'Deep learning', 'data'),
  ('tensorflow', 'TensorFlow', 'data'),
  ('pytorch', 'PyTorch', 'data'),
  ('scikit-learn', 'scikit-learn', 'data'),
  ('natural-language-processing', 'Natural language processing', 'data'),
  ('computer-vision', 'Computer vision', 'data'),
  ('time-series-analysis', 'Time series analysis', 'data'),
  ('business-intelligence', 'Business intelligence', 'data'),
  ('dashboard-design', 'Dashboard design', 'data'),
  ('kpi-definition', 'KPI definition', 'data'),
  ('data-storytelling', 'Data storytelling', 'data'),
  ('aws', 'AWS', 'cloud'),
  ('google-cloud-platform', 'Google Cloud Platform', 'cloud'),
  ('microsoft-azure', 'Microsoft Azure', 'cloud'),
  ('cloudflare', 'Cloudflare', 'cloud'),
  ('docker', 'Docker', 'cloud'),
  ('kubernetes', 'Kubernetes', 'cloud'),
  ('ci-cd', 'CI/CD', 'cloud'),
  ('github-actions', 'GitHub Actions', 'cloud'),
  ('jenkins', 'Jenkins', 'cloud'),
  ('gitlab-ci', 'GitLab CI', 'cloud'),
  ('terraform', 'Terraform', 'cloud'),
  ('ansible', 'Ansible', 'cloud'),
  ('linux-administration', 'Linux administration', 'cloud'),
  ('nginx', 'Nginx', 'cloud'),
  ('apache', 'Apache', 'cloud'),
  ('load-balancing', 'Load balancing', 'cloud'),
  ('serverless', 'Serverless', 'cloud'),
  ('lambda-functions', 'Lambda functions', 'cloud'),
  ('monitoring', 'Monitoring', 'cloud'),
  ('logging', 'Logging', 'cloud'),
  ('grafana', 'Grafana', 'cloud'),
  ('prometheus', 'Prometheus', 'cloud'),
  ('networking-basics', 'Networking basics', 'cloud'),
  ('dns', 'DNS', 'cloud'),
  ('cloud-cost-management', 'Cloud cost management', 'cloud'),
  ('infrastructure-as-code', 'Infrastructure as code', 'cloud'),
  ('site-reliability', 'Site reliability', 'cloud'),
  ('incident-response', 'Incident response', 'cloud'),
  ('cybersecurity-fundamentals', 'Cybersecurity fundamentals', 'security'),
  ('network-security', 'Network security', 'security'),
  ('penetration-testing', 'Penetration testing', 'security'),
  ('owasp-top-10', 'OWASP Top 10', 'security'),
  ('encryption', 'Encryption', 'security'),
  ('secure-coding', 'Secure coding', 'security'),
  ('vulnerability-assessment', 'Vulnerability assessment', 'security'),
  ('identity-and-access-management', 'Identity and access management', 'security'),
  ('security-auditing', 'Security auditing', 'security'),
  ('firewall-configuration', 'Firewall configuration', 'security'),
  ('ethical-hacking', 'Ethical hacking', 'security'),
  ('incident-forensics', 'Incident forensics', 'security'),
  ('manual-testing', 'Manual testing', 'qa'),
  ('automated-testing', 'Automated testing', 'qa'),
  ('selenium', 'Selenium', 'qa'),
  ('cypress', 'Cypress', 'qa'),
  ('playwright', 'Playwright', 'qa'),
  ('appium', 'Appium', 'qa'),
  ('junit', 'JUnit', 'qa'),
  ('pytest', 'PyTest', 'qa'),
  ('jest', 'Jest', 'qa'),
  ('test-case-design', 'Test case design', 'qa'),
  ('bug-reporting', 'Bug reporting', 'qa'),
  ('regression-testing', 'Regression testing', 'qa'),
  ('performance-testing', 'Performance testing', 'qa'),
  ('jmeter', 'JMeter', 'qa'),
  ('postman', 'Postman', 'qa'),
  ('api-testing', 'API testing', 'qa'),
  ('load-testing', 'Load testing', 'qa'),
  ('test-planning', 'Test planning', 'qa'),
  ('quality-assurance-processes', 'Quality assurance processes', 'qa'),
  ('user-acceptance-testing', 'User acceptance testing', 'qa'),
  ('figma', 'Figma', 'design'),
  ('adobe-xd', 'Adobe XD', 'design'),
  ('sketch', 'Sketch', 'design'),
  ('adobe-photoshop', 'Adobe Photoshop', 'design'),
  ('adobe-illustrator', 'Adobe Illustrator', 'design'),
  ('adobe-indesign', 'Adobe InDesign', 'design'),
  ('canva', 'Canva', 'design'),
  ('coreldraw', 'CorelDRAW', 'design'),
  ('ui-design', 'UI design', 'design'),
  ('ux-design', 'UX design', 'design'),
  ('wireframing', 'Wireframing', 'design'),
  ('prototyping', 'Prototyping', 'design'),
  ('design-systems', 'Design systems', 'design'),
  ('typography', 'Typography', 'design'),
  ('colour-theory', 'Colour theory', 'design'),
  ('layout-design', 'Layout design', 'design'),
  ('iconography', 'Iconography', 'design'),
  ('logo-design', 'Logo design', 'design'),
  ('brand-identity', 'Brand identity', 'design'),
  ('print-design', 'Print design', 'design'),
  ('packaging-design', 'Packaging design', 'design'),
  ('motion-graphics', 'Motion graphics', 'design'),
  ('adobe-after-effects', 'Adobe After Effects', 'design'),
  ('adobe-premiere-pro', 'Adobe Premiere Pro', 'design'),
  ('video-editing', 'Video editing', 'design'),
  ('3d-modelling', '3D modelling', 'design'),
  ('blender', 'Blender', 'design'),
  ('autocad', 'AutoCAD', 'design'),
  ('solidworks', 'SolidWorks', 'design'),
  ('user-research', 'User research', 'design'),
  ('usability-testing', 'Usability testing', 'design'),
  ('information-architecture', 'Information architecture', 'design'),
  ('accessibility-design', 'Accessibility design', 'design'),
  ('interaction-design', 'Interaction design', 'design'),
  ('design-handoff', 'Design handoff', 'design'),
  ('digital-marketing', 'Digital marketing', 'marketing'),
  ('search-engine-optimisation', 'Search engine optimisation', 'marketing'),
  ('search-engine-marketing', 'Search engine marketing', 'marketing'),
  ('google-ads', 'Google Ads', 'marketing'),
  ('facebook-ads', 'Facebook Ads', 'marketing'),
  ('meta-business-suite', 'Meta Business Suite', 'marketing'),
  ('social-media-marketing', 'Social media marketing', 'marketing'),
  ('content-marketing', 'Content marketing', 'marketing'),
  ('email-marketing', 'Email marketing', 'marketing'),
  ('marketing-automation', 'Marketing automation', 'marketing'),
  ('google-analytics', 'Google Analytics', 'marketing'),
  ('conversion-rate-optimisation', 'Conversion rate optimisation', 'marketing'),
  ('copywriting', 'Copywriting', 'marketing'),
  ('ad-copywriting', 'Ad copywriting', 'marketing'),
  ('influencer-marketing', 'Influencer marketing', 'marketing'),
  ('affiliate-marketing', 'Affiliate marketing', 'marketing'),
  ('brand-management', 'Brand management', 'marketing'),
  ('market-research', 'Market research', 'marketing'),
  ('competitor-analysis', 'Competitor analysis', 'marketing'),
  ('customer-segmentation', 'Customer segmentation', 'marketing'),
  ('campaign-planning', 'Campaign planning', 'marketing'),
  ('marketing-strategy', 'Marketing strategy', 'marketing'),
  ('public-relations', 'Public relations', 'marketing'),
  ('event-marketing', 'Event marketing', 'marketing'),
  ('youtube-marketing', 'YouTube marketing', 'marketing'),
  ('tiktok-marketing', 'TikTok marketing', 'marketing'),
  ('linkedin-marketing', 'LinkedIn marketing', 'marketing'),
  ('whatsapp-business', 'WhatsApp Business', 'marketing'),
  ('e-commerce-marketing', 'E-commerce marketing', 'marketing'),
  ('growth-hacking', 'Growth hacking', 'marketing'),
  ('funnel-analysis', 'Funnel analysis', 'marketing'),
  ('landing-page-optimisation', 'Landing page optimisation', 'marketing'),
  ('marketing-budgeting', 'Marketing budgeting', 'marketing'),
  ('business-analysis', 'Business analysis', 'business'),
  ('requirements-gathering', 'Requirements gathering', 'business'),
  ('stakeholder-management', 'Stakeholder management', 'business'),
  ('process-mapping', 'Process mapping', 'business'),
  ('bpmn', 'BPMN', 'business'),
  ('gap-analysis', 'Gap analysis', 'business'),
  ('swot-analysis', 'SWOT analysis', 'business'),
  ('feasibility-study', 'Feasibility study', 'business'),
  ('business-case-writing', 'Business case writing', 'business'),
  ('project-management', 'Project management', 'business'),
  ('agile', 'Agile', 'business'),
  ('scrum', 'Scrum', 'business'),
  ('kanban', 'Kanban', 'business'),
  ('jira', 'Jira', 'business'),
  ('trello', 'Trello', 'business'),
  ('asana', 'Asana', 'business'),
  ('risk-management', 'Risk management', 'business'),
  ('change-management', 'Change management', 'business'),
  ('vendor-management', 'Vendor management', 'business'),
  ('operations-management', 'Operations management', 'business'),
  ('supply-chain-basics', 'Supply chain basics', 'business'),
  ('inventory-management', 'Inventory management', 'business'),
  ('procurement', 'Procurement', 'business'),
  ('logistics', 'Logistics', 'business'),
  ('contract-management', 'Contract management', 'business'),
  ('strategic-planning', 'Strategic planning', 'business'),
  ('product-management', 'Product management', 'business'),
  ('product-roadmapping', 'Product roadmapping', 'business'),
  ('user-story-writing', 'User story writing', 'business'),
  ('backlog-grooming', 'Backlog grooming', 'business'),
  ('sprint-planning', 'Sprint planning', 'business'),
  ('consulting-skills', 'Consulting skills', 'business'),
  ('client-management', 'Client management', 'business'),
  ('financial-accounting', 'Financial accounting', 'finance'),
  ('managerial-accounting', 'Managerial accounting', 'finance'),
  ('bookkeeping', 'Bookkeeping', 'finance'),
  ('journal-entries', 'Journal entries', 'finance'),
  ('trial-balance', 'Trial balance', 'finance'),
  ('balance-sheet-preparation', 'Balance sheet preparation', 'finance'),
  ('income-statement-preparation', 'Income statement preparation', 'finance'),
  ('cash-flow-statement', 'Cash flow statement', 'finance'),
  ('bank-reconciliation', 'Bank reconciliation', 'finance'),
  ('accounts-payable', 'Accounts payable', 'finance'),
  ('accounts-receivable', 'Accounts receivable', 'finance'),
  ('payroll-processing', 'Payroll processing', 'finance'),
  ('taxation-bangladesh', 'Taxation Bangladesh', 'finance'),
  ('vat-compliance', 'VAT compliance', 'finance'),
  ('income-tax-return', 'Income tax return', 'finance'),
  ('auditing', 'Auditing', 'finance'),
  ('internal-controls', 'Internal controls', 'finance'),
  ('ifrs', 'IFRS', 'finance'),
  ('ias', 'IAS', 'finance'),
  ('financial-analysis', 'Financial analysis', 'finance'),
  ('ratio-analysis', 'Ratio analysis', 'finance'),
  ('financial-modelling', 'Financial modelling', 'finance'),
  ('valuation', 'Valuation', 'finance'),
  ('budgeting', 'Budgeting', 'finance'),
  ('forecasting', 'Forecasting', 'finance'),
  ('cost-accounting', 'Cost accounting', 'finance'),
  ('working-capital-management', 'Working capital management', 'finance'),
  ('investment-analysis', 'Investment analysis', 'finance'),
  ('capital-budgeting', 'Capital budgeting', 'finance'),
  ('risk-assessment', 'Risk assessment', 'finance'),
  ('tally', 'Tally', 'finance'),
  ('quickbooks', 'QuickBooks', 'finance'),
  ('sap-fico', 'SAP FICO', 'finance'),
  ('erp-systems', 'ERP systems', 'finance'),
  ('credit-analysis', 'Credit analysis', 'finance'),
  ('banking-operations', 'Banking operations', 'finance'),
  ('microfinance', 'Microfinance', 'finance'),
  ('insurance-basics', 'Insurance basics', 'finance'),
  ('recruitment', 'Recruitment', 'hr'),
  ('talent-sourcing', 'Talent sourcing', 'hr'),
  ('cv-screening', 'CV screening', 'hr'),
  ('interviewing', 'Interviewing', 'hr'),
  ('onboarding', 'Onboarding', 'hr'),
  ('employee-engagement', 'Employee engagement', 'hr'),
  ('performance-management', 'Performance management', 'hr'),
  ('kpi-setting', 'KPI setting', 'hr'),
  ('training-and-development', 'Training and development', 'hr'),
  ('learning-needs-analysis', 'Learning needs analysis', 'hr'),
  ('hr-policy-writing', 'HR policy writing', 'hr'),
  ('bangladesh-labour-act', 'Bangladesh Labour Act', 'hr'),
  ('payroll-administration', 'Payroll administration', 'hr'),
  ('compensation-and-benefits', 'Compensation and benefits', 'hr'),
  ('hris', 'HRIS', 'hr'),
  ('employee-relations', 'Employee relations', 'hr'),
  ('conflict-resolution', 'Conflict resolution', 'hr'),
  ('exit-interviews', 'Exit interviews', 'hr'),
  ('workforce-planning', 'Workforce planning', 'hr'),
  ('organisational-development', 'Organisational development', 'hr'),
  ('diversity-and-inclusion', 'Diversity and inclusion', 'hr'),
  ('hr-analytics', 'HR analytics', 'hr'),
  ('content-writing', 'Content writing', 'content'),
  ('blog-writing', 'Blog writing', 'content'),
  ('technical-writing', 'Technical writing', 'content'),
  ('creative-writing', 'Creative writing', 'content'),
  ('editing', 'Editing', 'content'),
  ('proofreading', 'Proofreading', 'content'),
  ('bangla-content-writing', 'Bangla content writing', 'content'),
  ('translation', 'Translation', 'content'),
  ('transcription', 'Transcription', 'content'),
  ('script-writing', 'Script writing', 'content'),
  ('storyboarding', 'Storyboarding', 'content'),
  ('storytelling', 'Storytelling', 'content'),
  ('research-writing', 'Research writing', 'content'),
  ('report-writing', 'Report writing', 'content'),
  ('proposal-writing', 'Proposal writing', 'content'),
  ('grant-writing', 'Grant writing', 'content'),
  ('journalism', 'Journalism', 'content'),
  ('social-media-copy', 'Social media copy', 'content'),
  ('newsletter-writing', 'Newsletter writing', 'content'),
  ('podcast-production', 'Podcast production', 'content'),
  ('photography', 'Photography', 'content'),
  ('videography', 'Videography', 'content'),
  ('voice-over', 'Voice-over', 'content'),
  ('communication', 'Communication', 'soft'),
  ('english-communication', 'English communication', 'soft'),
  ('bangla-communication', 'Bangla communication', 'soft'),
  ('presentation-skills', 'Presentation skills', 'soft'),
  ('public-speaking', 'Public speaking', 'soft'),
  ('active-listening', 'Active listening', 'soft'),
  ('written-communication', 'Written communication', 'soft'),
  ('teamwork', 'Teamwork', 'soft'),
  ('collaboration', 'Collaboration', 'soft'),
  ('leadership', 'Leadership', 'soft'),
  ('delegation', 'Delegation', 'soft'),
  ('mentoring', 'Mentoring', 'soft'),
  ('time-management', 'Time management', 'soft'),
  ('prioritisation', 'Prioritisation', 'soft'),
  ('problem-solving', 'Problem solving', 'soft'),
  ('critical-thinking', 'Critical thinking', 'soft'),
  ('analytical-thinking', 'Analytical thinking', 'soft'),
  ('attention-to-detail', 'Attention to detail', 'soft'),
  ('adaptability', 'Adaptability', 'soft'),
  ('resilience', 'Resilience', 'soft'),
  ('self-motivation', 'Self-motivation', 'soft'),
  ('initiative', 'Initiative', 'soft'),
  ('emotional-intelligence', 'Emotional intelligence', 'soft'),
  ('empathy', 'Empathy', 'soft'),
  ('negotiation', 'Negotiation', 'soft'),
  ('persuasion', 'Persuasion', 'soft'),
  ('conflict-management', 'Conflict management', 'soft'),
  ('decision-making', 'Decision making', 'soft'),
  ('networking', 'Networking', 'soft'),
  ('customer-service', 'Customer service', 'soft'),
  ('cross-cultural-communication', 'Cross-cultural communication', 'soft'),
  ('remote-work-discipline', 'Remote work discipline', 'soft'),
  ('feedback-receiving', 'Feedback receiving', 'soft'),
  ('continuous-learning', 'Continuous learning', 'soft'),
  ('git', 'Git', 'tools'),
  ('github', 'GitHub', 'tools'),
  ('gitlab', 'GitLab', 'tools'),
  ('bitbucket', 'Bitbucket', 'tools'),
  ('visual-studio-code', 'Visual Studio Code', 'tools'),
  ('intellij-idea', 'IntelliJ IDEA', 'tools'),
  ('android-studio', 'Android Studio', 'tools'),
  ('xcode', 'Xcode', 'tools'),
  ('slack', 'Slack', 'tools'),
  ('notion', 'Notion', 'tools'),
  ('confluence', 'Confluence', 'tools'),
  ('microsoft-word', 'Microsoft Word', 'tools'),
  ('microsoft-powerpoint', 'Microsoft PowerPoint', 'tools'),
  ('microsoft-teams', 'Microsoft Teams', 'tools'),
  ('google-workspace', 'Google Workspace', 'tools'),
  ('zoom', 'Zoom', 'tools'),
  ('miro', 'Miro', 'tools'),
  ('airtable', 'Airtable', 'tools'),
  ('zapier', 'Zapier', 'tools'),
  ('chatgpt-prompting', 'ChatGPT prompting', 'tools'),
  ('ai-tool-literacy', 'AI tool literacy', 'tools')
on conflict (slug) do update set name = excluded.name, category = excluded.category;
