-- School subjects, interests and career fields.
-- Subjects follow the Bangladeshi SSC/HSC syllabus, because that is what a
-- student will be looking for when they scan the list for their own.
-- Generated from supabase/seed/*.txt.

insert into public.subjects (slug, name, category, sort_order) values
  ('physics', 'Physics', 'sciences', 0),
  ('chemistry', 'Chemistry', 'sciences', 1),
  ('biology', 'Biology', 'sciences', 2),
  ('higher-mathematics', 'Higher mathematics', 'sciences', 3),
  ('mathematics', 'Mathematics', 'sciences', 4),
  ('general-science', 'General science', 'sciences', 5),
  ('environmental-science', 'Environmental science', 'sciences', 6),
  ('geology', 'Geology', 'sciences', 7),
  ('astronomy', 'Astronomy', 'sciences', 8),
  ('biotechnology', 'Biotechnology', 'sciences', 9),
  ('zoology', 'Zoology', 'sciences', 10),
  ('botany', 'Botany', 'sciences', 11),
  ('agricultural-science', 'Agricultural science', 'sciences', 12),
  ('health-science', 'Health science', 'sciences', 13),
  ('psychology', 'Psychology', 'sciences', 14),
  ('statistics', 'Statistics', 'sciences', 15),
  ('accounting', 'Accounting', 'commerce', 0),
  ('business-studies', 'Business studies', 'commerce', 1),
  ('business-organisation-and-management', 'Business organisation and management', 'commerce', 2),
  ('finance-and-banking', 'Finance and banking', 'commerce', 3),
  ('economics', 'Economics', 'commerce', 4),
  ('marketing', 'Marketing', 'commerce', 5),
  ('entrepreneurship', 'Entrepreneurship', 'commerce', 6),
  ('cost-accounting', 'Cost accounting', 'commerce', 7),
  ('commercial-geography', 'Commercial geography', 'commerce', 8),
  ('business-mathematics', 'Business mathematics', 'commerce', 9),
  ('production-management', 'Production management', 'commerce', 10),
  ('history', 'History', 'humanities', 0),
  ('geography', 'Geography', 'humanities', 1),
  ('civics-and-good-governance', 'Civics and good governance', 'humanities', 2),
  ('sociology', 'Sociology', 'humanities', 3),
  ('social-work', 'Social work', 'humanities', 4),
  ('logic', 'Logic', 'humanities', 5),
  ('philosophy', 'Philosophy', 'humanities', 6),
  ('political-science', 'Political science', 'humanities', 7),
  ('islamic-history-and-culture', 'Islamic history and culture', 'humanities', 8),
  ('anthropology', 'Anthropology', 'humanities', 9),
  ('home-science', 'Home science', 'humanities', 10),
  ('child-development', 'Child development', 'humanities', 11),
  ('bangla-first-paper', 'Bangla first paper', 'languages', 0),
  ('bangla-second-paper', 'Bangla second paper', 'languages', 1),
  ('english-first-paper', 'English first paper', 'languages', 2),
  ('english-second-paper', 'English second paper', 'languages', 3),
  ('arabic', 'Arabic', 'languages', 4),
  ('urdu', 'Urdu', 'languages', 5),
  ('hindi', 'Hindi', 'languages', 6),
  ('french', 'French', 'languages', 7),
  ('german', 'German', 'languages', 8),
  ('japanese', 'Japanese', 'languages', 9),
  ('chinese', 'Chinese', 'languages', 10),
  ('sanskrit', 'Sanskrit', 'languages', 11),
  ('pali', 'Pali', 'languages', 12),
  ('information-and-communication-technology', 'Information and communication technology', 'technology', 0),
  ('computer-science', 'Computer science', 'technology', 1),
  ('computer-fundamentals', 'Computer fundamentals', 'technology', 2),
  ('programming', 'Programming', 'technology', 3),
  ('web-design', 'Web design', 'technology', 4),
  ('graphic-design', 'Graphic design', 'technology', 5),
  ('electronics', 'Electronics', 'technology', 6),
  ('electrical-engineering-basics', 'Electrical engineering basics', 'technology', 7),
  ('mechanical-drawing', 'Mechanical drawing', 'technology', 8),
  ('robotics', 'Robotics', 'technology', 9),
  ('islamic-studies', 'Islamic studies', 'religion', 0),
  ('hindu-religion', 'Hindu religion', 'religion', 1),
  ('christian-religion', 'Christian religion', 'religion', 2),
  ('buddhist-religion', 'Buddhist religion', 'religion', 3),
  ('quran-majeed', 'Quran majeed', 'religion', 4),
  ('hadith', 'Hadith', 'religion', 5),
  ('fiqh', 'Fiqh', 'religion', 6),
  ('islamic-history', 'Islamic history', 'religion', 7),
  ('fine-art', 'Fine art', 'arts', 0),
  ('drawing-and-painting', 'Drawing and painting', 'arts', 1),
  ('music', 'Music', 'arts', 2),
  ('drama', 'Drama', 'arts', 3),
  ('dance', 'Dance', 'arts', 4),
  ('photography', 'Photography', 'arts', 5),
  ('film-studies', 'Film studies', 'arts', 6),
  ('design-and-technology', 'Design and technology', 'arts', 7),
  ('craft', 'Craft', 'arts', 8),
  ('physical-education', 'Physical education', 'other', 0),
  ('health-and-physical-education', 'Health and physical education', 'other', 1),
  ('career-education', 'Career education', 'other', 2),
  ('agriculture', 'Agriculture', 'other', 3),
  ('textile', 'Textile', 'other', 4),
  ('food-and-nutrition', 'Food and nutrition', 'other', 5),
  ('library-science', 'Library science', 'other', 6),
  ('general-knowledge', 'General knowledge', 'other', 7),
  ('life-skills', 'Life skills', 'other', 8),
  ('media-studies', 'Media studies', 'other', 9)
on conflict (slug) do update set name = excluded.name, category = excluded.category;

insert into public.interests (slug, name, category, sort_order) values
  ('drawing', 'Drawing', 'creative', 0),
  ('painting', 'Painting', 'creative', 1),
  ('photography', 'Photography', 'creative', 2),
  ('videography', 'Videography', 'creative', 3),
  ('video-editing', 'Video editing', 'creative', 4),
  ('graphic-design', 'Graphic design', 'creative', 5),
  ('creative-writing', 'Creative writing', 'creative', 6),
  ('poetry', 'Poetry', 'creative', 7),
  ('blogging', 'Blogging', 'creative', 8),
  ('music-production', 'Music production', 'creative', 9),
  ('playing-an-instrument', 'Playing an instrument', 'creative', 10),
  ('singing', 'Singing', 'creative', 11),
  ('dancing', 'Dancing', 'creative', 12),
  ('acting', 'Acting', 'creative', 13),
  ('filmmaking', 'Filmmaking', 'creative', 14),
  ('animation', 'Animation', 'creative', 15),
  ('crafts', 'Crafts', 'creative', 16),
  ('calligraphy', 'Calligraphy', 'creative', 17),
  ('football', 'Football', 'sport', 0),
  ('cricket', 'Cricket', 'sport', 1),
  ('badminton', 'Badminton', 'sport', 2),
  ('table-tennis', 'Table tennis', 'sport', 3),
  ('basketball', 'Basketball', 'sport', 4),
  ('volleyball', 'Volleyball', 'sport', 5),
  ('swimming', 'Swimming', 'sport', 6),
  ('running', 'Running', 'sport', 7),
  ('cycling', 'Cycling', 'sport', 8),
  ('gym-and-fitness', 'Gym and fitness', 'sport', 9),
  ('martial-arts', 'Martial arts', 'sport', 10),
  ('chess', 'Chess', 'sport', 11),
  ('carrom', 'Carrom', 'sport', 12),
  ('athletics', 'Athletics', 'sport', 13),
  ('programming', 'Programming', 'technical', 0),
  ('web-development', 'Web development', 'technical', 1),
  ('app-development', 'App development', 'technical', 2),
  ('robotics', 'Robotics', 'technical', 3),
  ('electronics', 'Electronics', 'technical', 4),
  ('gaming', 'Gaming', 'technical', 5),
  ('game-development', 'Game development', 'technical', 6),
  ('3d-modelling', '3D modelling', 'technical', 7),
  ('cybersecurity', 'Cybersecurity', 'technical', 8),
  ('artificial-intelligence', 'Artificial intelligence', 'technical', 9),
  ('data-analysis', 'Data analysis', 'technical', 10),
  ('building-computers', 'Building computers', 'technical', 11),
  ('science-olympiad', 'Science olympiad', 'academic', 0),
  ('maths-olympiad', 'Maths olympiad', 'academic', 1),
  ('physics-olympiad', 'Physics olympiad', 'academic', 2),
  ('debating', 'Debating', 'academic', 3),
  ('public-speaking', 'Public speaking', 'academic', 4),
  ('model-united-nations', 'Model United Nations', 'academic', 5),
  ('quiz-competitions', 'Quiz competitions', 'academic', 6),
  ('research', 'Research', 'academic', 7),
  ('reading', 'Reading', 'academic', 8),
  ('language-learning', 'Language learning', 'academic', 9),
  ('astronomy', 'Astronomy', 'academic', 10),
  ('volunteering', 'Volunteering', 'social', 0),
  ('community-service', 'Community service', 'social', 1),
  ('teaching-others', 'Teaching others', 'social', 2),
  ('mentoring', 'Mentoring', 'social', 3),
  ('event-organising', 'Event organising', 'social', 4),
  ('club-leadership', 'Club leadership', 'social', 5),
  ('fundraising', 'Fundraising', 'social', 6),
  ('social-media-management', 'Social media management', 'social', 7),
  ('blood-donation-drives', 'Blood donation drives', 'social', 8),
  ('environmental-campaigns', 'Environmental campaigns', 'social', 9),
  ('entrepreneurship', 'Entrepreneurship', 'business', 0),
  ('small-business', 'Small business', 'business', 1),
  ('freelancing', 'Freelancing', 'business', 2),
  ('trading', 'Trading', 'business', 3),
  ('investing', 'Investing', 'business', 4),
  ('marketing', 'Marketing', 'business', 5),
  ('sales', 'Sales', 'business', 6),
  ('startups', 'Startups', 'business', 7),
  ('cooking', 'Cooking', 'lifestyle', 0),
  ('baking', 'Baking', 'lifestyle', 1),
  ('gardening', 'Gardening', 'lifestyle', 2),
  ('travelling', 'Travelling', 'lifestyle', 3),
  ('hiking', 'Hiking', 'lifestyle', 4),
  ('fishing', 'Fishing', 'lifestyle', 5),
  ('pets-and-animals', 'Pets and animals', 'lifestyle', 6),
  ('fashion', 'Fashion', 'lifestyle', 7),
  ('podcasts', 'Podcasts', 'lifestyle', 8),
  ('journalling', 'Journalling', 'lifestyle', 9),
  ('board-games', 'Board games', 'lifestyle', 10),
  ('collecting', 'Collecting', 'lifestyle', 11)
on conflict (slug) do update set name = excluded.name, category = excluded.category;

insert into public.career_fields (slug, name, subjects, sort_order) values
  ('engineering', 'Engineering', array['Physics','Higher mathematics','Mathematics','Chemistry']::text[], 0),
  ('computer-science', 'Computer science and software', array['Information and communication technology','Higher mathematics','Physics']::text[], 1),
  ('medicine', 'Medicine and health', array['Biology','Chemistry','Physics']::text[], 2),
  ('pharmacy', 'Pharmacy', array['Chemistry','Biology']::text[], 3),
  ('nursing', 'Nursing and allied health', array['Biology','Health science']::text[], 4),
  ('business', 'Business and management', array['Business studies','Accounting','Economics']::text[], 5),
  ('accounting', 'Accounting and finance', array['Accounting','Business mathematics','Economics']::text[], 6),
  ('economics', 'Economics', array['Economics','Mathematics','Statistics']::text[], 7),
  ('banking', 'Banking and insurance', array['Finance and banking','Accounting']::text[], 8),
  ('marketing', 'Marketing and advertising', array['Marketing','Business studies']::text[], 9),
  ('law', 'Law', array['Civics and good governance','History','Logic']::text[], 10),
  ('architecture', 'Architecture and planning', array['Physics','Higher mathematics','Fine art']::text[], 11),
  ('design', 'Design and creative arts', array['Fine art','Drawing and painting','Graphic design']::text[], 12),
  ('media', 'Media and journalism', array['English first paper','Media studies','Film studies']::text[], 13),
  ('education', 'Teaching and education', array['Bangla first paper','English first paper','Psychology']::text[], 14),
  ('psychology', 'Psychology and counselling', array['Psychology','Biology']::text[], 15),
  ('social-science', 'Social sciences', array['Sociology','Political science','Anthropology']::text[], 16),
  ('public-admin', 'Public administration and civil service', array['Civics and good governance','Political science']::text[], 17),
  ('international-relations', 'International relations', array['Political science','History','English first paper']::text[], 18),
  ('agriculture', 'Agriculture and food science', array['Agricultural science','Biology','Chemistry']::text[], 19),
  ('environment', 'Environment and sustainability', array['Environmental science','Geography','Biology']::text[], 20),
  ('biotech', 'Biotechnology and genetics', array['Biology','Chemistry']::text[], 21),
  ('statistics', 'Statistics and data science', array['Statistics','Higher mathematics']::text[], 22),
  ('mathematics', 'Mathematics', array['Higher mathematics','Mathematics']::text[], 23),
  ('physics', 'Physics', array['Physics','Higher mathematics']::text[], 24),
  ('chemistry', 'Chemistry', array['Chemistry','Mathematics']::text[], 25),
  ('textile', 'Textile and apparel engineering', array['Physics','Chemistry','Textile']::text[], 26),
  ('civil-engineering', 'Civil engineering', array['Physics','Higher mathematics']::text[], 27),
  ('electrical-engineering', 'Electrical and electronic engineering', array['Physics','Higher mathematics','Electronics']::text[], 28),
  ('mechanical-engineering', 'Mechanical engineering', array['Physics','Higher mathematics','Mechanical drawing']::text[], 29),
  ('marine', 'Marine and naval studies', array['Physics','Mathematics']::text[], 30),
  ('aviation', 'Aviation and aeronautics', array['Physics','Higher mathematics']::text[], 31),
  ('hospitality', 'Hospitality and tourism', array['Geography','English first paper']::text[], 32),
  ('sports-science', 'Sports and physical education', array['Physical education','Biology']::text[], 33),
  ('languages', 'Languages and literature', array['English first paper','Bangla first paper','Arabic']::text[], 34),
  ('islamic-studies', 'Islamic studies', array['Islamic studies','Arabic','Quran majeed']::text[], 35),
  ('fine-arts', 'Fine arts and performance', array['Fine art','Music','Drama']::text[], 36),
  ('library', 'Library and information science', array['Library science','English first paper']::text[], 37),
  ('development', 'Development studies and NGO work', array['Sociology','Economics','Social work']::text[], 38),
  ('undecided', 'Not sure yet', '{}'::text[], 999)
on conflict (slug) do update set name = excluded.name, subjects = excluded.subjects;
