-- Topping the subject list up past a hundred, and the Bangladeshi
-- university list to sixty, so a student almost always finds their own
-- rather than falling through to the free-text escape.

insert into public.subjects (slug, name, category, sort_order) values
  ('physics', 'Physics', 'sciences', 0),
  ('chemistry', 'Chemistry', 'sciences', 1),
  ('biology', 'Biology', 'sciences', 2),
  ('higher-mathematics', 'Higher mathematics', 'sciences', 3),
  ('mathematics', 'Mathematics', 'sciences', 4),
  ('general-science', 'General science', 'sciences', 5),
  ('environmental-science', 'Environmental science', 'sciences', 6),
  ('geology', 'Geology', 'sciences', 7),
  ('astronomy', 'Astronomy', 'sciences', 8),
  ('biotechnology', 'Biotechnology', 'sciences', 9),
  ('zoology', 'Zoology', 'sciences', 10),
  ('botany', 'Botany', 'sciences', 11),
  ('agricultural-science', 'Agricultural science', 'sciences', 12),
  ('health-science', 'Health science', 'sciences', 13),
  ('psychology', 'Psychology', 'sciences', 14),
  ('statistics', 'Statistics', 'sciences', 15),
  ('accounting', 'Accounting', 'commerce', 0),
  ('business-studies', 'Business studies', 'commerce', 1),
  ('business-organisation-and-management', 'Business organisation and management', 'commerce', 2),
  ('finance-and-banking', 'Finance and banking', 'commerce', 3),
  ('economics', 'Economics', 'commerce', 4),
  ('marketing', 'Marketing', 'commerce', 5),
  ('entrepreneurship', 'Entrepreneurship', 'commerce', 6),
  ('cost-accounting', 'Cost accounting', 'commerce', 7),
  ('commercial-geography', 'Commercial geography', 'commerce', 8),
  ('business-mathematics', 'Business mathematics', 'commerce', 9),
  ('production-management', 'Production management', 'commerce', 10),
  ('history', 'History', 'humanities', 0),
  ('geography', 'Geography', 'humanities', 1),
  ('civics-and-good-governance', 'Civics and good governance', 'humanities', 2),
  ('sociology', 'Sociology', 'humanities', 3),
  ('social-work', 'Social work', 'humanities', 4),
  ('logic', 'Logic', 'humanities', 5),
  ('philosophy', 'Philosophy', 'humanities', 6),
  ('political-science', 'Political science', 'humanities', 7),
  ('islamic-history-and-culture', 'Islamic history and culture', 'humanities', 8),
  ('anthropology', 'Anthropology', 'humanities', 9),
  ('home-science', 'Home science', 'humanities', 10),
  ('child-development', 'Child development', 'humanities', 11),
  ('bangla-first-paper', 'Bangla first paper', 'languages', 0),
  ('bangla-second-paper', 'Bangla second paper', 'languages', 1),
  ('english-first-paper', 'English first paper', 'languages', 2),
  ('english-second-paper', 'English second paper', 'languages', 3),
  ('arabic', 'Arabic', 'languages', 4),
  ('urdu', 'Urdu', 'languages', 5),
  ('hindi', 'Hindi', 'languages', 6),
  ('french', 'French', 'languages', 7),
  ('german', 'German', 'languages', 8),
  ('japanese', 'Japanese', 'languages', 9),
  ('chinese', 'Chinese', 'languages', 10),
  ('sanskrit', 'Sanskrit', 'languages', 11),
  ('pali', 'Pali', 'languages', 12),
  ('information-and-communication-technology', 'Information and communication technology', 'technology', 0),
  ('computer-science', 'Computer science', 'technology', 1),
  ('computer-fundamentals', 'Computer fundamentals', 'technology', 2),
  ('programming', 'Programming', 'technology', 3),
  ('web-design', 'Web design', 'technology', 4),
  ('graphic-design', 'Graphic design', 'technology', 5),
  ('electronics', 'Electronics', 'technology', 6),
  ('electrical-engineering-basics', 'Electrical engineering basics', 'technology', 7),
  ('mechanical-drawing', 'Mechanical drawing', 'technology', 8),
  ('robotics', 'Robotics', 'technology', 9),
  ('islamic-studies', 'Islamic studies', 'religion', 0),
  ('hindu-religion', 'Hindu religion', 'religion', 1),
  ('christian-religion', 'Christian religion', 'religion', 2),
  ('buddhist-religion', 'Buddhist religion', 'religion', 3),
  ('quran-majeed', 'Quran majeed', 'religion', 4),
  ('hadith', 'Hadith', 'religion', 5),
  ('fiqh', 'Fiqh', 'religion', 6),
  ('islamic-history', 'Islamic history', 'religion', 7),
  ('fine-art', 'Fine art', 'arts', 0),
  ('drawing-and-painting', 'Drawing and painting', 'arts', 1),
  ('music', 'Music', 'arts', 2),
  ('drama', 'Drama', 'arts', 3),
  ('dance', 'Dance', 'arts', 4),
  ('photography', 'Photography', 'arts', 5),
  ('film-studies', 'Film studies', 'arts', 6),
  ('design-and-technology', 'Design and technology', 'arts', 7),
  ('craft', 'Craft', 'arts', 8),
  ('physical-education', 'Physical education', 'other', 0),
  ('health-and-physical-education', 'Health and physical education', 'other', 1),
  ('career-education', 'Career education', 'other', 2),
  ('agriculture', 'Agriculture', 'other', 3),
  ('textile', 'Textile', 'other', 4),
  ('food-and-nutrition', 'Food and nutrition', 'other', 5),
  ('library-science', 'Library science', 'other', 6),
  ('general-knowledge', 'General knowledge', 'other', 7),
  ('life-skills', 'Life skills', 'other', 8),
  ('media-studies', 'Media studies', 'other', 9),
  ('applied-physics', 'Applied physics', 'sciences', 0),
  ('applied-chemistry', 'Applied chemistry', 'sciences', 1),
  ('organic-chemistry', 'Organic chemistry', 'sciences', 2),
  ('inorganic-chemistry', 'Inorganic chemistry', 'sciences', 3),
  ('physical-chemistry', 'Physical chemistry', 'sciences', 4),
  ('microbiology', 'Microbiology', 'sciences', 5),
  ('genetics', 'Genetics', 'sciences', 6),
  ('human-anatomy', 'Human anatomy', 'sciences', 7),
  ('physiology', 'Physiology', 'sciences', 8),
  ('biochemistry', 'Biochemistry', 'sciences', 9),
  ('soil-science', 'Soil science', 'sciences', 10),
  ('fisheries', 'Fisheries', 'sciences', 11),
  ('veterinary-science', 'Veterinary science', 'sciences', 12),
  ('nutrition', 'Nutrition', 'sciences', 13),
  ('auditing', 'Auditing', 'commerce', 0),
  ('taxation', 'Taxation', 'commerce', 1),
  ('business-law', 'Business law', 'commerce', 2),
  ('insurance', 'Insurance', 'commerce', 3),
  ('banking-operations', 'Banking operations', 'commerce', 4),
  ('international-business', 'International business', 'commerce', 5),
  ('human-resource-management', 'Human resource management', 'commerce', 6),
  ('supply-chain-management', 'Supply chain management', 'commerce', 7),
  ('investment-analysis', 'Investment analysis', 'commerce', 8),
  ('archaeology', 'Archaeology', 'humanities', 0),
  ('peace-and-conflict-studies', 'Peace and conflict studies', 'humanities', 1),
  ('gender-studies', 'Gender studies', 'humanities', 2),
  ('development-studies', 'Development studies', 'humanities', 3),
  ('public-administration', 'Public administration', 'humanities', 4),
  ('international-relations', 'International relations', 'humanities', 5),
  ('criminology', 'Criminology', 'humanities', 6),
  ('journalism', 'Journalism', 'humanities', 7),
  ('mass-communication', 'Mass communication', 'humanities', 8),
  ('data-structures', 'Data structures', 'technology', 0),
  ('database-systems', 'Database systems', 'technology', 1),
  ('networking', 'Networking', 'technology', 2),
  ('operating-systems', 'Operating systems', 'technology', 3),
  ('software-engineering', 'Software engineering', 'technology', 4),
  ('artificial-intelligence', 'Artificial intelligence', 'technology', 5),
  ('machine-learning', 'Machine learning', 'technology', 6),
  ('cyber-security', 'Cyber security', 'technology', 7),
  ('mechatronics', 'Mechatronics', 'technology', 8),
  ('civil-drafting', 'Civil drafting', 'technology', 9)
on conflict (slug) do update set name = excluded.name, category = excluded.category;

insert into public.universities (name, short_name, city_id)
select v.name, v.short_name, c.id from (values
  ('Bangladesh University of Business and Technology', 'BUBT', 'Dhaka'),
  ('World University of Bangladesh', 'WUB', 'Dhaka'),
  ('Northern University Bangladesh', 'NUB', 'Dhaka'),
  ('City University', 'CityU', 'Dhaka'),
  ('Manarat International University', 'MIU', 'Dhaka'),
  ('Primeasia University', 'PAU', 'Dhaka'),
  ('Uttara University', 'UU', 'Dhaka'),
  ('Bangladesh University', 'BU', 'Dhaka'),
  ('Sonargaon University', 'SU', 'Dhaka'),
  ('European University of Bangladesh', 'EUB', 'Dhaka'),
  ('Britannia University', 'BrU', 'Cumilla'),
  ('Feni University', 'FU', 'Feni'),
  ('Bangabandhu Sheikh Mujib Medical University', 'BSMMU', 'Dhaka'),
  ('Chittagong Veterinary and Animal Sciences University', 'CVASU', 'Chattogram'),
  ('Sylhet Agricultural University', 'SAU Sylhet', 'Sylhet')
) as v(name, short_name, city)
left join public.cities c on c.name = v.city
on conflict (name) do nothing;

-- Every seeded city belongs to Bangladesh; the country now drives which
-- list is shown, so this has to be right.
update public.cities set country_id = (select id from public.countries where iso2 = 'BD')
  where country_id is null;
